# DATAFRAMES

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("/Volumes/MACBACKUP/workspaceDlake/dlake/base/fornecedores_DB1.parquet")
display(df)

,id,nome,endereco,telefone,origem
0,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,DB1
1,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,DB1
2,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,DB1
3,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,DB1
4,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,DB1
5,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,DB1
6,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,DB1
7,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,DB1
8,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,DB1
9,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,DB1
10,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,DB1
11,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,DB1
12,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,DB1
13,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,DB1
14,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,DB1
15,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,DB1
16,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,DB1

In [3]:
df = pd.read_parquet("/Volumes/MACBACKUP/workspaceDlake/dlake/base/produtos_DB1.parquet")
display(df)

    id           nome       preco origem
0    1             Ab  142.839996    DB1
1    2        Dolorum  854.780029    DB1
2    3       Nesciunt   60.580002    DB1
3    4       Nesciunt   89.239998    DB1
4    5        Numquam   76.750000    DB1
5    6         Labore  446.350006    DB1
6    7            Sit  803.080017    DB1
7    8          Ipsam  745.919983    DB1
8    9         Maxime  955.010010    DB1
9   10          Culpa  251.509995    DB1
10  11          Nulla  886.049988    DB1
11  12       Pariatur  231.199997    DB1
12  13             Et  308.519989    DB1
13  14      Inventore  556.239990    DB1
14  15            Cum  721.000000    DB1
15  16         Quidem  239.539993    DB1
16  17       Incidunt  698.609985    DB1
17  18  Reprehenderit  844.799988    DB1
18  19      Molestias  598.570007    DB1
19  20           Quos  555.640015    DB1
20  21              A  321.109985    DB1
21  22     Voluptates  579.450012    DB1
22  23          Culpa   95.440002    DB1
23  24     Asperiores  494.209991    DB1
24  25     Laboriosam  682.530029    DB1

In [4]:
df = pd.read_parquet("/Volumes/MACBACKUP/workspaceDlake/dlake/base/vendas_DB1.parquet")
display(df)

,id,vendedor_id,produto_id,fornecedor_id,quantidade,valor_total,data,origem
0,1,5,7,4,3,2409.239990,2020-02-24,DB1
1,2,5,9,4,1,955.010010,2023-04-06,DB1
2,3,4,7,3,7,5621.560059,2020-03-08,DB1
3,4,3,10,5,3,754.530029,2020-04-16,DB1
4,5,3,10,3,3,754.530029,2024-11-14,DB1
5,6,4,4,2,7,624.679993,2024-02-20,DB1
6,7,3,3,3,8,484.640015,2023-06-10,DB1
7,8,3,2,5,3,2564.340088,2024-10-16,DB1
8,9,3,1,2,1,142.839996,2023-05-22,DB1
9,10,8,24,16,4,1976.839966,2022-04-15,DB1
10,11,9,25,15,1,682.530029,2024-07-08,DB1
11,12,6,23,17,10,954.400024,2022-12-09,DB1
12,13,6,25,16,9,6142.770020,2024-10-25,DB1
13,14,7,21,15,2,642.219971,2020-10-05,DB1
14,15,8,25,16,10,6825.299805,2020-10-12,DB1
15,16,9,23,16,10,954.400024,2024-06-24,DB1

In [6]:
con.close()

NameError: name 'con' is not defined

In [5]:
df = pd.read_parquet("/Volumes/MACBACKUP/workspaceDlake/dlake/base/vendedores_DB1.parquet")
display(df)

   id                     nome                           email  idade origem
0   1              Lunna Brito    rochamaria-laura@example.com     34    DB1
1   2            Lucca Rezende              wpinto@example.net     40    DB1
2   3          Anna Liz Farias  aparecidaana-clara@example.org     24    DB1
3   4    Dra. Mirella Mendonça    cardosoguilherme@example.com     37    DB1
4   5      João Lucas Caldeira      enricoda-rocha@example.net     47    DB1
5   6          Allana Carvalho             bguerra@example.net     47    DB1
6   7              Stella Rios    pedro-henrique26@example.net     30    DB1
7   8  Sra. Emanuelly Oliveira              lais10@example.net     39    DB1
8   9          Theodoro Pastor            raquel39@example.com     35    DB1
9  10            Maria Barbosa       cecilianovaes@example.com     46    DB1

In [9]:
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/vendedores_DB1.parquet")
display(df)

,idVendedor,nomeVendedor,emailVendedor,idadeVendedor,origem
0,1,Lunna Brito,rochamaria-laura@example.com,34,DB1
1,2,Lucca Rezende,wpinto@example.net,40,DB1
2,3,Anna Liz Farias,aparecidaana-clara@example.org,24,DB1
3,4,Dra. Mirella Mendonça,cardosoguilherme@example.com,37,DB1
4,5,João Lucas Caldeira,enricoda-rocha@example.net,47,DB1
5,6,Allana Carvalho,bguerra@example.net,47,DB1
6,7,Stella Rios,pedro-henrique26@example.net,30,DB1
7,8,Sra. Emanuelly Oliveira,lais10@example.net,39,DB1
8,9,Theodoro Pastor,raquel39@example.com,35,DB1
9,10,Maria Barbosa,cecilianovaes@example.com,46,DB1

In [21]:
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/silverAnaliticsFornecedor.parquet")
display(df)

,idFornecedor,nomeFornecedor,enderecoFornecedor,telefoneFornecedor,origem
0,1,Peixoto,"Fazenda de Mendes, 75\nFlavio De Oliveira\n125...",+55 (084) 3458-5032,DB2
1,1,Silva,"Núcleo Cirino, 15\nZilah Sposito\n31034777 da ...",51 9164 7450,DB3
2,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,DB1
3,2,Pereira Ltda.,Recanto Mathias Pinto\nVila Antena Montanhês\n...,+55 41 9150 3848,DB3
4,2,Rios - ME,"Rodovia Carvalho, 7\nMaravilha\n46952400 Barbo...",(081) 3766 5246,DB2
5,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,DB1
6,3,Fernandes,"Praia Benjamin Pires, 5\nPrimeiro De Maio\n120...",+55 (021) 2696 7754,DB2
7,3,Ribeiro,"Condomínio da Paz, 45\nVila Madre Gertrudes 2ª...",+55 (071) 2426-3024,DB3
8,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,DB1
9,4,da Rocha Costa - ME,Colônia da Mota\nVila Nova Cachoeirinha 1ª Seç...,+55 51 5440 1025,DB3
10,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,DB1
11,4,Siqueira,"Trevo Stella Nunes, 91\nHorto\n23002-548 Viana...",+55 (061) 3329 4089,DB2
12,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,DB1
13,5,da Cruz,"Chácara de Azevedo, 8\nAndiroba\n32181858 Corr...",+55 (071) 7957-9959,DB2
14,5,Novais Cunha - EI,"Vereda de Duarte, 54\nBelmonte\n65200190 Brito...",+55 61 4968-4664,DB3
15,6,Cavalcanti,"Vale Emanuella Aragão, 642\nConjunto Bonsucess...",0500 951 3449,DB3
16,6,Correia Ltda.,"Lagoa Pacheco, 7\nVila Antena Montanhês\n70794...",+55 (011) 1661-4945,DB2
17,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,DB1
18,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,DB1
19,7,Montenegro,Conjunto de da Cunha\nVentosa\n93333-194 Peixo...,+55 (011) 7682 5672,DB2
20,7,Teixeira,"Conjunto Vieira, 51\nCoração De Jesus\n65858-7...",71 4186 5633,DB3
21,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,DB1
22,8,Cardoso Sampaio - EI,"Área Stella da Cunha, 75\nSerrano\n38312-764 O...",+55 (084) 3347 8077,DB3
23,8,Garcia Ltda.,"Conjunto de da Paz, 69\nComiteco\n53674-877 Po...",31 3082 7972,DB2
24,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,DB1
25,9,Aparecida,"Esplanada de Correia, 7\nConjunto Celso Machad...",0500 141 9316,DB2
26,9,Vargas Siqueira - EI,Pátio Monteiro\nVila Satélite\n64016037 Moraes...,+55 41 8839 2342,DB3
27,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,DB1
28,10,Casa Grande,"Avenida Porto, 5\nCandelaria\n74910808 Porto d...",+55 (011) 9204 8080,DB2
29,10,Castro - EI,"Loteamento da Rocha, 67\nCasa Branca\n23020484...",(011) 3767-9350,DB3
30,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,DB1
31,11,Costa Freitas S.A.,"Distrito de Costela, 444\nUniversitário\n15870...",(021) 2606-8420,DB2
32,11,Abreu S.A.,"Setor Leão, 33\nNovo São Lucas\n03210-265 Pint...",+55 (084) 3144 8782,DB3
33,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,DB1
34,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,DB1
35,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,DB1
36,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,DB1
37,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,DB1
38,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,DB1

In [11]:
dfFor = pd.read_parquet("/Users/danielcarloss7s/Downloads/02-02-2025-17-16-24_files_list/silverAnaliticsFornecedor.parquet")
dfPro = pd.read_parquet("/Users/danielcarloss7s/Downloads/02-02-2025-17-16-24_files_list/silverAnaliticsProdutos.parquet")
dfVend = pd.read_parquet("/Users/danielcarloss7s/Downloads/02-02-2025-17-16-24_files_list/silverAnaliticsVendas.parquet")
dfVedor = pd.read_parquet("/Users/danielcarloss7s/Downloads/02-02-2025-17-16-24_files_list/silverAnaliticsVendedor.parquet")

In [12]:
display(dfFor)
display(dfPro)
display(dfVend)
display(dfVedor)

,idFornecedor,nomeFornecedor,enderecoFornecedor,telefoneFornecedor,origem
0,1,Peixoto,"Fazenda de Mendes, 75\nFlavio De Oliveira\n125...",+55 (084) 3458-5032,DB2
1,1,Silva,"Núcleo Cirino, 15\nZilah Sposito\n31034777 da ...",51 9164 7450,DB3
2,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,DB1
3,2,Pereira Ltda.,Recanto Mathias Pinto\nVila Antena Montanhês\n...,+55 41 9150 3848,DB3
4,2,Rios - ME,"Rodovia Carvalho, 7\nMaravilha\n46952400 Barbo...",(081) 3766 5246,DB2
5,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,DB1
6,3,Fernandes,"Praia Benjamin Pires, 5\nPrimeiro De Maio\n120...",+55 (021) 2696 7754,DB2
7,3,Ribeiro,"Condomínio da Paz, 45\nVila Madre Gertrudes 2ª...",+55 (071) 2426-3024,DB3
8,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,DB1
9,4,da Rocha Costa - ME,Colônia da Mota\nVila Nova Cachoeirinha 1ª Seç...,+55 51 5440 1025,DB3
10,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,DB1
11,4,Siqueira,"Trevo Stella Nunes, 91\nHorto\n23002-548 Viana...",+55 (061) 3329 4089,DB2
12,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,DB1
13,5,da Cruz,"Chácara de Azevedo, 8\nAndiroba\n32181858 Corr...",+55 (071) 7957-9959,DB2
14,5,Novais Cunha - EI,"Vereda de Duarte, 54\nBelmonte\n65200190 Brito...",+55 61 4968-4664,DB3
15,6,Cavalcanti,"Vale Emanuella Aragão, 642\nConjunto Bonsucess...",0500 951 3449,DB3
16,6,Correia Ltda.,"Lagoa Pacheco, 7\nVila Antena Montanhês\n70794...",+55 (011) 1661-4945,DB2
17,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,DB1
18,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,DB1
19,7,Montenegro,Conjunto de da Cunha\nVentosa\n93333-194 Peixo...,+55 (011) 7682 5672,DB2
20,7,Teixeira,"Conjunto Vieira, 51\nCoração De Jesus\n65858-7...",71 4186 5633,DB3
21,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,DB1
22,8,Cardoso Sampaio - EI,"Área Stella da Cunha, 75\nSerrano\n38312-764 O...",+55 (084) 3347 8077,DB3
23,8,Garcia Ltda.,"Conjunto de da Paz, 69\nComiteco\n53674-877 Po...",31 3082 7972,DB2
24,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,DB1
25,9,Aparecida,"Esplanada de Correia, 7\nConjunto Celso Machad...",0500 141 9316,DB2
26,9,Vargas Siqueira - EI,Pátio Monteiro\nVila Satélite\n64016037 Moraes...,+55 41 8839 2342,DB3
27,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,DB1
28,10,Casa Grande,"Avenida Porto, 5\nCandelaria\n74910808 Porto d...",+55 (011) 9204 8080,DB2
29,10,Castro - EI,"Loteamento da Rocha, 67\nCasa Branca\n23020484...",(011) 3767-9350,DB3
30,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,DB1
31,11,Costa Freitas S.A.,"Distrito de Costela, 444\nUniversitário\n15870...",(021) 2606-8420,DB2
32,11,Abreu S.A.,"Setor Leão, 33\nNovo São Lucas\n03210-265 Pint...",+55 (084) 3144 8782,DB3
33,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,DB1
34,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,DB1
35,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,DB1
36,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,DB1
37,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,DB1
38,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,DB1

    idProduto nomeProduto       preco origem
0           1          Ab  142.839996    DB1
1           1  Voluptates  490.410004    DB3
2           1         Eum  633.320007    DB2
3           2       Earum  805.190002    DB2
4           2      Beatae  178.160004    DB3
..        ...         ...         ...    ...
61         22    Deleniti  458.519989    DB3
62         23   Accusamus  661.229980    DB3
63         23       Culpa   95.440002    DB1
64         24  Asperiores  494.209991    DB1
65         25  Laboriosam  682.530029    DB1

[66 rows x 4 columns]

,idVendas,idVendedor,idProdutos,idFornecedor,quantidade,valorTotal,data,origem
0,1,5,1,3,1,490.410004,2021-10-02,DB3
1,1,2,4,1,1,70.839996,2024-10-30,DB2
2,1,5,7,4,3,2409.239990,2020-02-24,DB1
3,2,2,1,4,3,1899.959961,2020-08-10,DB2
4,2,4,8,4,8,1567.920044,2021-05-08,DB3
5,2,5,9,4,1,955.010010,2023-04-06,DB1
6,3,3,15,4,10,8787.599609,2023-05-03,DB3
7,3,4,7,3,7,5621.560059,2020-03-08,DB1
8,3,1,6,7,6,1645.739990,2024-06-06,DB2
9,4,3,10,5,3,754.530029,2020-04-16,DB1
10,4,1,11,6,2,761.780029,2023-01-11,DB2
11,4,3,9,6,5,4833.149902,2022-09-30,DB3
12,5,3,10,3,3,754.530029,2024-11-14,DB1
13,5,2,6,1,1,997.039978,2023-11-10,DB3
14,5,3,7,1,5,1120.750000,2023-04-11,DB2
15,6,1,3,5,9,8698.679688,2020-09-19,DB2
16,6,3,8,1,2,391.980011,2021-08-18,DB3
17,6,4,4,2,7,624.679993,2024-02-20,DB1
18,7,3,3,3,8,484.640015,2023-06-10,DB1
19,7,5,3,1,6,1359.780029,2020-07-20,DB3
20,7,4,3,6,3,2899.560059,2023-01-13,DB2
21,8,5,2,1,3,534.479980,2024-08-28,DB3
22,8,3,2,5,3,2564.340088,2024-10-16,DB1
23,8,3,3,6,6,5799.120117,2020-09-15,DB2
24,9,3,1,2,1,142.839996,2023-05-22,DB1
25,9,4,4,7,9,637.559998,2020-03-05,DB2
26,9,3,14,5,6,829.739990,2023-05-07,DB3
27,10,10,20,10,9,1326.780029,2022-08-21,DB3
28,10,8,24,16,4,1976.839966,2022-04-15,DB1
29,10,9,14,9,5,2729.500000,2021-06-22,DB2
30,11,9,25,15,1,682.530029,2024-07-08,DB1
31,11,10,22,7,4,1834.079956,2021-07-10,DB3
32,11,9,17,9,3,2233.679932,2020-03-03,DB2
33,12,6,23,17,10,954.400024,2022-12-09,DB1
34,12,6,23,10,7,4628.609863,2024-12-21,DB3
35,12,8,17,10,8,5956.479980,2023-09-22,DB2
36,13,6,25,16,9,6142.770020,2024-10-25,DB1
37,13,10,22,9,1,458.519989,2020-05-07,DB3
38,13,7,17,8,2,1489.119995,2022-08-15,DB2
39,14,7,21,15,2,642.219971,2020-10-05,DB1
40,14,8,17,8,4,2978.239990,2021-12-31,DB2
41,14,9,19,11,2,903.000000,2024-02-25,DB3
42,15,8,25,16,10,6825.299805,2020-10-12,DB1
43,15,10,14,9,8,4367.200195,2022-09-04,DB2
44,15,6,20,11,8,1179.359985,2023-07-17,DB3
45,16,9,23,16,10,954.400024,2024-06-24,DB1
46,16,7,14,9,10,5459.000000,2021-06-16,DB2
47,16,7,23,8,7,4628.609863,2024-09-01,DB3
48,17,7,16,10,7,4371.919922,2023-03-23,DB3
49,17,8,14,11,1,545.900024,2022-01-20,DB2
50,18,10,17,10,8,5956.479980,2022-08-14,DB2
51,18,10,20,8,10,1474.199951,2024-04-21,DB3
52,19,10,14,8,1,545.900024,2022-05-21,DB2
53,19,8,19,7,6,2709.000000,2022-02-04,DB3
54,20,6,18,10,9,8885.969727,2020-05-11,DB3
55,21,7,19,10,9,4063.500000,2023-06-28,DB3

,idVendedor,nomeVendedor,emailVendedor,idadeVendedor,origem
0,1,Lunna Brito,rochamaria-laura@example.com,34,DB1
1,1,Bruna Abreu,bferreira@example.com,22,DB2
2,1,Carolina Novais,enrico47@example.org,33,DB3
3,2,Lucca Rezende,wpinto@example.net,40,DB1
4,2,Evelyn Freitas,maria-luisanascimento@example.com,35,DB3
5,2,Isabella Pimenta,camargogabrielly@example.net,46,DB2
6,3,Igor Vieira,borgesmelissa@example.com,46,DB2
7,3,Anna Liz Farias,aparecidaana-clara@example.org,24,DB1
8,3,Brayan Garcia,souzamelissa@example.net,28,DB3
9,4,Davi Lucas Souza,tlima@example.com,42,DB2
10,4,Bruna Novaes,nunesnoah@example.org,26,DB3
11,4,Dra. Mirella Mendonça,cardosoguilherme@example.com,37,DB1
12,5,João Vitor Sá,benjaminazevedo@example.com,27,DB2
13,5,Ana Júlia Costa,caldeiramaria-eduarda@example.com,49,DB3
14,5,João Lucas Caldeira,enricoda-rocha@example.net,47,DB1
15,6,Allana Carvalho,bguerra@example.net,47,DB1
16,6,Maria Júlia Oliveira,antony39@example.org,47,DB2
17,6,Mariah Silva,enzo-gabrielteixeira@example.com,40,DB3
18,7,Srta. Cecília Siqueira,mendoncakevin@example.net,24,DB3
19,7,Mateus Sá,zoeporto@example.net,40,DB2
20,7,Stella Rios,pedro-henrique26@example.net,30,DB1
21,8,João Lucas Pacheco,hda-mota@example.net,35,DB3
22,8,Sra. Emanuelly Oliveira,lais10@example.net,39,DB1
23,8,Maria Júlia Pereira,gabrielaaragao@example.com,40,DB2
24,9,Oliver Ramos,saramendes@example.com,20,DB2
25,9,Manuela Caldeira,henry71@example.org,45,DB3
26,9,Theodoro Pastor,raquel39@example.com,35,DB1
27,10,Maria Barbosa,cecilianovaes@example.com,46,DB1
28,10,Maria Liz Novaes,laura51@example.org,36,DB3
29,10,Carolina Silveira,correiabrenda@example.org,32,DB2

In [ ]:
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/goldVendas (1).parquet")
display(df)

In [41]:
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/fornecedores_DB1.parquet")
display(df)

,id,nome,endereco,telefone,dtcriação,origem
0,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
1,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
2,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
3,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
4,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
5,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
6,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
7,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
8,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
9,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
10,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
11,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
12,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
13,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
14,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
15,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
16,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
17,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
18,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
19,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
20,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
21,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
22,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1
23,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
24,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
25,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
26,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
27,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
28,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
29,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
30,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
31,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
32,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
33,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
34,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
35,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
36,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
37,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
38,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
39,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
40,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
41,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
42,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
43,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
44,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
45,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1

# TESTES DE PY VIGENTE

In [26]:
import duckdb
import os
import glob

# Caminho onde os arquivos Parquet foram baixados
local_download_path = "./downloads_landzone/landzone"

# Identifica todos os arquivos Parquet
parquet_files = glob.glob(os.path.join(local_download_path, "*.parquet"))

# Dicionário para armazenar conexões DuckDB
db_connections = {}

# Processar cada arquivo Parquet
for file in parquet_files:
    # Extrair nome do arquivo (ex: fornecedores_db1.parquet)
    filename = os.path.basename(file)
    
    # Separar nome base e banco (ex: "fornecedores", "db1")
    table_name, db_name = filename.replace(".parquet", "").rsplit("_", 1)

    # Criar conexão com o banco correspondente
    db_path = f"./downloads_landzone/{db_name}.duckdb"
    
    if db_name not in db_connections:
        db_connections[db_name] = duckdb.connect(db_path)

    conn = db_connections[db_name]

    # Criar tabela e importar os dados
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS {table_name} AS 
        SELECT * FROM read_parquet('{file}');
    """)
    print(f"Arquivo {filename} importado para {db_name}.duckdb na tabela {table_name}.")

# Fechar conexões
for conn in db_connections.values():
    conn.close()

print("Importação concluída!")

Arquivo fornecedores_db1.parquet importado para db1.duckdb na tabela fornecedores.
Arquivo fornecedores_db2.parquet importado para db2.duckdb na tabela fornecedores.
Arquivo fornecedores_db3.parquet importado para db3.duckdb na tabela fornecedores.
Arquivo produtos_db1.parquet importado para db1.duckdb na tabela produtos.
Arquivo produtos_db2.parquet importado para db2.duckdb na tabela produtos.
Arquivo produtos_db3.parquet importado para db3.duckdb na tabela produtos.
Arquivo vendas_db1.parquet importado para db1.duckdb na tabela vendas.
Arquivo vendas_db2.parquet importado para db2.duckdb na tabela vendas.
Arquivo vendas_db3.parquet importado para db3.duckdb na tabela vendas.
Arquivo vendedores_db1.parquet importado para db1.duckdb na tabela vendedores.
Arquivo vendedores_db2.parquet importado para db2.duckdb na tabela vendedores.
Arquivo vendedores_db3.parquet importado para db3.duckdb na tabela vendedores.
Importação concluída!

In [30]:
import duckdb
import os
from minio import Minio
from minio.error import S3Error

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nome do bucket de destino
dest_bucket = "datalake"

# Estrutura das pastas no MinIO
base_prefix = "bronze"
sub_prefix_mapping = {
    "db1": "bronzedb1",
    "db2": "bronzedb2",
    "db3": "bronzedb3"
}

# Lista de bancos DuckDB
databases = ["db1", "db2", "db3"]

# Criar pasta local temporária para armazenar os Parquets antes do upload
local_parquet_path = "./parquet_export"
os.makedirs(local_parquet_path, exist_ok=True)

# Processar cada banco
for db in databases:
    db_path = f"./downloads_landzone/{db}.duckdb"
    conn = duckdb.connect(db_path)

    # Obter todas as tabelas do banco
    tables = conn.execute("SHOW TABLES").fetchall()
    
    for table in tables:
        table_name = table[0]

        # Caminho do arquivo Parquet
        parquet_file = os.path.join(local_parquet_path, f"{table_name}_{db}.parquet")

        # Exportar os dados para Parquet
        conn.execute(f"COPY {table_name} TO '{parquet_file}' (FORMAT PARQUET);")
        print(f"Exportado: {parquet_file}")

        # Caminho no MinIO
        minio_path = f"{base_prefix}/{sub_prefix_mapping[db]}/{table_name}.parquet"

        # Enviar para MinIO
        try:
            minio_client.fput_object(dest_bucket, minio_path, parquet_file)
            print(f"Enviado para MinIO: {dest_bucket}/{minio_path}")
        except S3Error as e:
            print(f"Erro ao enviar {parquet_file} para MinIO: {e}")

    # Fechar conexão com o banco DuckDB
    conn.close()

print("Processo concluído! 🎯")

Exportado: ./parquet_export/fornecedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/fornecedores.parquet
Exportado: ./parquet_export/produtos_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/produtos.parquet
Exportado: ./parquet_export/vendas_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendas.parquet
Exportado: ./parquet_export/vendedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendedores.parquet
Exportado: ./parquet_export/fornecedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/fornecedores.parquet
Exportado: ./parquet_export/produtos_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/produtos.parquet
Exportado: ./parquet_export/vendas_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendas.parquet
Exportado: ./parquet_export/vendedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendedores.parquet
Exportado: ./parquet_export/fornecedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/fornecedores.parquet
Exportado: ./parquet_export/produtos_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/produtos.parquet
Exportado: ./parquet_export/vendas_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendas.parquet
Exportado: ./parquet_export/vendedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendedores.parquet
Processo concluído! 🎯

In [34]:
import duckdb
import os
from minio import Minio
from minio.error import S3Error

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nome do bucket de destino
dest_bucket = "datalake"

# Estrutura das pastas no MinIO
base_prefix = "bronze"
sub_prefix_mapping = {
    "db1": "bronzedb1",
    "db2": "bronzedb2",
    "db3": "bronzedb3"
}

# Lista de bancos DuckDB
databases = ["db1", "db2", "db3"]

# Criar pasta local temporária para armazenar os Parquets antes do upload
local_parquet_path = "./parquet_export"
os.makedirs(local_parquet_path, exist_ok=True)

# Processar cada banco
for db in databases:
    db_path = f"./downloads_landzone/{db}.duckdb"
    conn = duckdb.connect(db_path)

    # Obter todas as tabelas do banco
    tables = conn.execute("SHOW TABLES").fetchall()
    
    for table in tables:
        table_name = table[0]

        # Caminho do arquivo Parquet
        parquet_file = os.path.join(local_parquet_path, f"{table_name}_{db}.parquet")

        # Exportar os dados para Parquet
        conn.execute(f"COPY {table_name} TO '{parquet_file}' (FORMAT PARQUET);")
        print(f"Exportado: {parquet_file}")

        # Caminho no MinIO
        minio_path = f"{base_prefix}/{sub_prefix_mapping[db]}/{table_name}.parquet"

        # Enviar para MinIO
        try:
            minio_client.fput_object(dest_bucket, minio_path, parquet_file)
            print(f"Enviado para MinIO: {dest_bucket}/{minio_path}")

            # Excluir arquivo Parquet local após o upload
            os.remove(parquet_file)
            print(f"Arquivo local removido: {parquet_file}")

        except S3Error as e:
            print(f"Erro ao enviar {parquet_file} para MinIO: {e}")

    # Fechar conexão com o banco DuckDB
    conn.close()

# Remover a pasta temporária se estiver vazia
try:
    os.rmdir(local_parquet_path)
    print(f"Pasta removida: {local_parquet_path}")
except OSError:
    print(f"A pasta {local_parquet_path} não está vazia ou já foi removida.")

print("Processo concluído! 🎯")

Exportado: ./parquet_export/fornecedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db1.parquet
Exportado: ./parquet_export/produtos_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db1.parquet
Exportado: ./parquet_export/vendas_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db1.parquet
Exportado: ./parquet_export/vendedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db1.parquet
Exportado: ./parquet_export/fornecedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db2.parquet
Exportado: ./parquet_export/produtos_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db2.parquet
Exportado: ./parquet_export/vendas_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db2.parquet
Exportado: ./parquet_export/vendedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db2.parquet
Exportado: ./parquet_export/fornecedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db3.parquet
Exportado: ./parquet_export/produtos_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db3.parquet
Exportado: ./parquet_export/vendas_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db3.parquet
Exportado: ./parquet_export/vendedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db3.parquet
Pasta removida: ./parquet_export
Processo concluído! 🎯

In [36]:
import os
import duckdb
from minio import Minio
from minio.error import S3Error

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Buckets e estrutura de pastas no MinIO
source_bucket = "landzone"
dest_bucket = "datalake"
base_prefix = "bronze"

sub_prefix_mapping = {
    "db1": "bronzedb1",
    "db2": "bronzedb2",
    "db3": "bronzedb3"
}

# Criar pastas locais para downloads e exportação
landzone_path = "./downloads_landzone"
bronze_path = "./downloads_bronze"
parquet_export_path = "./parquet_export"

os.makedirs(landzone_path, exist_ok=True)
os.makedirs(bronze_path, exist_ok=True)
os.makedirs(parquet_export_path, exist_ok=True)

# Lista de bancos DuckDB
databases = ["db1", "db2", "db3"]

### 1. BAIXAR ARQUIVOS DA LANDZONE E IMPORTAR PARA O DUCKDB ###
objects = minio_client.list_objects(source_bucket, recursive=True)

for obj in objects:
    file_path = obj.object_name
    file_name = os.path.basename(file_path)

    # Identificar o banco correspondente
    for db, bronze_prefix in sub_prefix_mapping.items():
        if f"_{db}." in file_name:  # Exemplo: fornecedores_db1.parquet
            db_path = f"./{db}.duckdb"
            local_file = os.path.join(landzone_path, file_name)

            # Baixar o arquivo
            minio_client.fget_object(source_bucket, file_path, local_file)
            print(f"Baixado da Landzone: {local_file}")

            # Conectar ao banco e importar
            conn = duckdb.connect(db_path)
            table_name = file_name.replace(f"_{db}.parquet", "")
            conn.execute(f"CREATE TABLE IF NOT EXISTS {table_name} AS SELECT * FROM read_parquet('{local_file}')")
            print(f"Tabela {table_name} criada no banco {db}")

            conn.close()
            os.remove(local_file)  # Excluir o arquivo baixado
            print(f"Arquivo removido: {local_file}")

print("Importação da Landzone concluída!")

### 2. BAIXAR ARQUIVOS DA BRONZE E IMPORTAR PARA O MESMO DUCKDB ###
objects = minio_client.list_objects(dest_bucket, prefix="bronze/", recursive=True)

for obj in objects:
    file_path = obj.object_name
    file_name = os.path.basename(file_path)

    # Identificar o banco correspondente
    for bronze_prefix, db in sub_prefix_mapping.items():
        if file_path.startswith(f"bronze/{bronze_prefix}/"):
            db_path = f"./{db}.duckdb"
            local_file = os.path.join(bronze_path, file_name)

            # Baixar o arquivo
            minio_client.fget_object(dest_bucket, file_path, local_file)
            print(f"Baixado da Bronze: {local_file}")

            # Conectar ao banco e importar
            conn = duckdb.connect(db_path)
            table_name = file_name.replace(".parquet", "")
            conn.execute(f"CREATE TABLE IF NOT EXISTS {table_name} AS SELECT * FROM read_parquet('{local_file}')")
            print(f"Tabela {table_name} criada no banco {db}")

            conn.close()
            os.remove(local_file)  # Excluir o arquivo baixado
            print(f"Arquivo removido: {local_file}")

print("Importação da Bronze concluída!")

### 3. EXPORTAR DADOS DO DUCKDB PARA PARQUET E ENVIAR AO MINIO ###
for db in databases:
    db_path = f"./{db}.duckdb"
    conn = duckdb.connect(db_path)

    # Obter todas as tabelas
    tables = conn.execute("SHOW TABLES").fetchall()

    for table in tables:
        table_name = table[0]
        parquet_file = os.path.join(parquet_export_path, f"{table_name}_{db}.parquet")

        # Exportar dados para Parquet
        conn.execute(f"COPY {table_name} TO '{parquet_file}' (FORMAT PARQUET);")
        print(f"Exportado: {parquet_file}")

        # Caminho no MinIO
        minio_path = f"{base_prefix}/{sub_prefix_mapping[db]}/{table_name}.parquet"

        # Enviar para MinIO
        try:
            minio_client.fput_object(dest_bucket, minio_path, parquet_file)
            print(f"Enviado para MinIO: {dest_bucket}/{minio_path}")

            # Excluir arquivo Parquet local após o upload
            os.remove(parquet_file)
            print(f"Arquivo local removido: {parquet_file}")

        except S3Error as e:
            print(f"Erro ao enviar {parquet_file} para MinIO: {e}")

    conn.close()

# Remover pastas temporárias
try:
    os.rmdir(parquet_export_path)
    os.rmdir(landzone_path)
    os.rmdir(bronze_path)
    print("Pastas temporárias removidas!")
except OSError:
    print("Pastas não estavam vazias ou já foram removidas.")

print("Processo completo! 🚀")

Baixado da Landzone: ./downloads_landzone/fornecedores_db1.parquet
Tabela fornecedores criada no banco db1
Arquivo removido: ./downloads_landzone/fornecedores_db1.parquet
Baixado da Landzone: ./downloads_landzone/fornecedores_db2.parquet
Tabela fornecedores criada no banco db2
Arquivo removido: ./downloads_landzone/fornecedores_db2.parquet
Baixado da Landzone: ./downloads_landzone/fornecedores_db3.parquet
Tabela fornecedores criada no banco db3
Arquivo removido: ./downloads_landzone/fornecedores_db3.parquet
Baixado da Landzone: ./downloads_landzone/produtos_db1.parquet
Tabela produtos criada no banco db1
Arquivo removido: ./downloads_landzone/produtos_db1.parquet
Baixado da Landzone: ./downloads_landzone/produtos_db2.parquet
Tabela produtos criada no banco db2
Arquivo removido: ./downloads_landzone/produtos_db2.parquet
Baixado da Landzone: ./downloads_landzone/produtos_db3.parquet
Tabela produtos criada no banco db3
Arquivo removido: ./downloads_landzone/produtos_db3.parquet
Baixado da Landzone: ./downloads_landzone/vendas_db1.parquet
Tabela vendas criada no banco db1
Arquivo removido: ./downloads_landzone/vendas_db1.parquet
Baixado da Landzone: ./downloads_landzone/vendas_db2.parquet
Tabela vendas criada no banco db2
Arquivo removido: ./downloads_landzone/vendas_db2.parquet
Baixado da Landzone: ./downloads_landzone/vendas_db3.parquet
Tabela vendas criada no banco db3
Arquivo removido: ./downloads_landzone/vendas_db3.parquet
Baixado da Landzone: ./downloads_landzone/vendedores_db1.parquet
Tabela vendedores criada no banco db1
Arquivo removido: ./downloads_landzone/vendedores_db1.parquet
Baixado da Landzone: ./downloads_landzone/vendedores_db2.parquet
Tabela vendedores criada no banco db2
Arquivo removido: ./downloads_landzone/vendedores_db2.parquet
Baixado da Landzone: ./downloads_landzone/vendedores_db3.parquet
Tabela vendedores criada no banco db3
Arquivo removido: ./downloads_landzone/vendedores_db3.parquet
Importação da Landzone concluída!
Importação da Bronze concluída!
Exportado: ./parquet_export/fornecedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db1.parquet
Exportado: ./parquet_export/produtos_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db1.parquet
Exportado: ./parquet_export/vendas_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db1.parquet
Exportado: ./parquet_export/vendedores_db1.parquet
Enviado para MinIO: datalake/bronze/bronzedb1/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db1.parquet
Exportado: ./parquet_export/fornecedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db2.parquet
Exportado: ./parquet_export/produtos_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db2.parquet
Exportado: ./parquet_export/vendas_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db2.parquet
Exportado: ./parquet_export/vendedores_db2.parquet
Enviado para MinIO: datalake/bronze/bronzedb2/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db2.parquet
Exportado: ./parquet_export/fornecedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/fornecedores.parquet
Arquivo local removido: ./parquet_export/fornecedores_db3.parquet
Exportado: ./parquet_export/produtos_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/produtos.parquet
Arquivo local removido: ./parquet_export/produtos_db3.parquet
Exportado: ./parquet_export/vendas_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendas.parquet
Arquivo local removido: ./parquet_export/vendas_db3.parquet
Exportado: ./parquet_export/vendedores_db3.parquet
Enviado para MinIO: datalake/bronze/bronzedb3/vendedores.parquet
Arquivo local removido: ./parquet_export/vendedores_db3.parquet
Pastas não estavam vazias ou já foram removidas.
Processo completo! 🚀

In [24]:
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/fornecedores_db1.parquet")
display(df)

,id,nome,endereco,telefone,dtcriação,origem
0,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
1,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
2,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
3,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
4,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
5,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
6,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
7,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
8,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
9,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
10,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
11,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
12,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
13,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
14,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
15,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
16,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
17,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
18,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
19,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
20,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
21,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
22,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1
23,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
24,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
25,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
26,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
27,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
28,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
29,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
30,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
31,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
32,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
33,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
34,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
35,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
36,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
37,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
38,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
39,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
40,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
41,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
42,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
43,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
44,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
45,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1

In [7]:
import pandas as pd
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/fornecedores_db1.parquet")
display(df)

,id,nome,endereco,telefone,dtcriação,origem
0,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
1,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
2,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
3,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
4,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
5,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
6,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
7,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
8,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
9,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
10,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
11,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
12,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
13,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
14,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
15,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
16,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
17,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
18,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
19,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
20,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
21,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
22,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1
23,1,Machado - ME,Estrada de Azevedo\nVila Nova\n33390-723 da Mo...,+55 81 5040-7669,2025-02-05 07:11:41,db1
24,2,Melo Martins Ltda.,"Passarela de Cardoso, 71\nVila Betânia\n38705-...",0500 859 7457,2025-02-05 07:11:41,db1
25,3,Pereira - EI,"Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n...",(011) 8144-8050,2025-02-05 07:11:41,db1
26,4,Casa Grande,"Distrito Julia Pastor, 9\nEstrela Do Oriente\n...",(041) 3565-8571,2025-02-05 07:11:41,db1
27,5,Sales,"Chácara de Pires, 9\nPindura Saia\n00870394 Pi...",(084) 2173-5590,2025-02-05 07:11:41,db1
28,6,Abreu,"Feira Nicolas Dias, 22\nGameleira\n00329079 da...",+55 71 3187-2758,2025-02-05 07:11:41,db1
29,7,Ribeiro,"Praia de da Mata, 8\nJoão Alfredo\n98866-706 F...",84 9622 9908,2025-02-05 07:11:41,db1
30,8,Costa Mendonça e Filhos,"Travessa Barros, 802\nCinquentenário\n45486-42...",0500 509 3592,2025-02-05 07:11:41,db1
31,9,Ribeiro,"Vale de Fogaça, 65\nAlto Dos Pinheiros\n258660...",71 9829-4069,2025-02-05 07:11:41,db1
32,10,Carvalho S.A.,"Colônia de Jesus, 14\nConjunto Taquaril\n62597...",+55 61 4893-9602,2025-02-05 07:11:41,db1
33,11,Nunes,Condomínio Almeida\nCidade Jardim\n47696-418 V...,+55 51 8469 7227,2025-02-05 07:11:41,db1
34,12,Viana Pereira S/A,"Estação Luiz Fernando da Rocha, 457\nJardim At...",31 4137-3148,2025-02-05 07:11:41,db1
35,13,Cavalcante,"Rua de Siqueira, 36\nMinas Brasil\n72670397 Co...",+55 21 7247-8470,2025-02-05 07:11:41,db1
36,14,Pinto Novais S/A,"Loteamento de Camargo, 53\nGraça\n28553492 Cam...",+55 (071) 0022-0612,2025-02-05 07:11:41,db1
37,15,da Rocha Ltda.,"Morro Castro, 68\nSão Jorge 3ª Seção\n88148889...",51 8478 8592,2025-02-05 07:11:41,db1
38,16,Sá,"Largo João Cirino, 644\nSaudade\n37173-020 Por...",(061) 0761 7014,2025-02-05 07:11:41,db1
39,17,da Cunha Sousa e Filhos,Via de Aparecida\nSanta Isabel\n47163-670 Cass...,+55 61 1689 8303,2025-02-05 07:11:41,db1
40,18,Farias - ME,"Núcleo Lunna Freitas, 26\nVila Nova Cachoeirin...",+55 51 3839 2286,2025-02-05 07:11:41,db1
41,19,Rios - ME,Rodovia Asafe Cavalcanti\nComiteco\n10407897 B...,+55 61 2295 0105,2025-02-05 07:11:41,db1
42,20,Macedo,"Via Freitas, 241\nAlto Das Antenas\n21448085 F...",21 2997 8905,2025-02-05 07:11:41,db1
43,21,das Neves S.A.,Avenida Isis Aparecida\nEstoril\n36007629 Abre...,0900 823 7906,2025-02-05 07:11:41,db1
44,22,Moreira,"Favela de Casa Grande, 83\nTres Marias\n174382...",+55 11 2443-4792,2025-02-05 07:11:41,db1
45,23,Fonseca,"Pátio Vargas, 18\nMala E Cuia\n69300419 Noguei...",(051) 2570 4520,2025-02-05 07:11:41,db1

# NOVO SCRIPT DE UPSERT

In [39]:
from minio import Minio
import duckdb
import os

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nome do bucket no MinIO
bucket_name = "landzone"

# Diretório temporário para armazenar os arquivos baixados
download_dir = "minio_downloads"
os.makedirs(download_dir, exist_ok=True)

# Conectar ao DuckDB e criar os schemas
db_path = "dados.duckdb"
conn = duckdb.connect(db_path)
schemas = ["db1", "db2", "db3"]

for schema in schemas:
    conn.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

# Listar arquivos no bucket
objects = minio_client.list_objects(bucket_name, recursive=True)

for obj in objects:
    file_name = obj.object_name  # Exemplo: "subdir/fornecedores_db1.parquet"

    if file_name.endswith(".parquet"):
        # Criar a estrutura de diretórios localmente, se necessário
        local_file = os.path.join(download_dir, file_name)
        os.makedirs(os.path.dirname(local_file), exist_ok=True)

        # Baixar o arquivo do MinIO
        minio_client.fget_object(bucket_name, file_name, local_file)

        # Determinar o schema com base no nome do arquivo
        if "_db1" in file_name:
            schema = "db1"
        elif "_db2" in file_name:
            schema = "db2"
        elif "_db3" in file_name:
            schema = "db3"
        else:
            print(f"Arquivo {file_name} ignorado (sem correspondência de schema).")
            continue

        # Nome da tabela sem a extensão e caracteres problemáticos
        table_name = os.path.basename(file_name).replace(".parquet", "").replace("-", "_").replace("/", "_")

        # Criar a tabela e importar os dados
        query = f"CREATE OR REPLACE TABLE {schema}.{table_name} AS SELECT * FROM read_parquet(?)"
        conn.execute(query, [local_file])  # Passando o caminho do arquivo como parâmetro

        print(f"Arquivo {file_name} carregado no schema {schema} como {table_name}")

# Fechar a conexão com o DuckDB
conn.close()

Arquivo landzone/fornecedores_db1.parquet carregado no schema db1 como fornecedores_db1
Arquivo landzone/fornecedores_db2.parquet carregado no schema db2 como fornecedores_db2
Arquivo landzone/fornecedores_db3.parquet carregado no schema db3 como fornecedores_db3
Arquivo landzone/produtos_db1.parquet carregado no schema db1 como produtos_db1
Arquivo landzone/produtos_db2.parquet carregado no schema db2 como produtos_db2
Arquivo landzone/produtos_db3.parquet carregado no schema db3 como produtos_db3
Arquivo landzone/vendas_db1.parquet carregado no schema db1 como vendas_db1
Arquivo landzone/vendas_db2.parquet carregado no schema db2 como vendas_db2
Arquivo landzone/vendas_db3.parquet carregado no schema db3 como vendas_db3
Arquivo landzone/vendedores_db1.parquet carregado no schema db1 como vendedores_db1
Arquivo landzone/vendedores_db2.parquet carregado no schema db2 como vendedores_db2
Arquivo landzone/vendedores_db3.parquet carregado no schema db3 como vendedores_db3

In [2]:
from minio import Minio
import duckdb
import os

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nome dos buckets e estrutura das camadas
buckets = {
    "landzone": ["db1", "db2", "db3"],  # landzone tem arquivos diretamente
    "datalake": ["bronzedb1", "bronzedb2", "bronzedb3"]  # bronze está dentro do datalake
}

# Prefixo para os arquivos bronze dentro do datalake
bronze_prefix = "bronze/"

# Diretório temporário para armazenar os arquivos baixados
download_dir = "minio_downloads"
os.makedirs(download_dir, exist_ok=True)

# Conectar ao DuckDB e criar os schemas
db_path = "dados.duckdb"
conn = duckdb.connect(db_path)

# Criar os schemas necessários
for schemas in buckets.values():
    for schema in schemas:
        conn.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

# Função para processar os arquivos de um bucket
def process_bucket(bucket_name, schemas, prefix=""):
    print(f"\n🔍 Listando arquivos no bucket '{bucket_name}' com prefixo '{prefix}'...")
    
    objects = list(minio_client.list_objects(bucket_name, prefix=prefix, recursive=True))
    
    if not objects:
        print(f"⚠️ Nenhum arquivo encontrado no bucket {bucket_name} com prefixo {prefix}!")
        return
    
    for obj in objects:
        file_name = obj.object_name  # Exemplo: "bronze/bronzedb1/fornecedores.parquet"
        print(f"📂 Encontrado: {file_name}")

        if file_name.endswith(".parquet"):
            # Criar a estrutura de diretórios localmente
            local_file = os.path.join(download_dir, os.path.basename(file_name))
            os.makedirs(os.path.dirname(local_file), exist_ok=True)

            # Baixar o arquivo do MinIO
            minio_client.fget_object(bucket_name, file_name, local_file)
            print(f"✅ Arquivo {file_name} baixado para {local_file}")

            # Determinar o schema correto pelo caminho da pasta (não pelo nome do arquivo)
            path_parts = file_name.split("/")
            if len(path_parts) > 2 and path_parts[1] in schemas:
                schema = path_parts[1]  # Exemplo: "bronzedb1"
            else:
                print(f"⚠️ Arquivo {file_name} ignorado (sem correspondência de schema).")
                continue

            # Nome da tabela sem extensão
            table_name = os.path.basename(file_name).replace(".parquet", "").replace("-", "_")
            print(f"📊 Criando tabela: {schema}.{table_name}")

            # Criar a tabela e importar os dados
            query = f"CREATE OR REPLACE TABLE {schema}.{table_name} AS SELECT * FROM read_parquet(?)"
            conn.execute(query, [local_file])  # Passando o caminho do arquivo como parâmetro
            print(f"✅ Arquivo {file_name} carregado no schema {schema} como {table_name}")

# Processar o bucket landzone normalmente
process_bucket("landzone", buckets["landzone"])

# Processar a camada bronze dentro do bucket datalake
process_bucket("datalake", buckets["datalake"], prefix=bronze_prefix)

# Fechar a conexão com o DuckDB
conn.close()
print("\n🎉 Processo concluído!")

🔍 Listando arquivos no bucket 'landzone' com prefixo ''...
📂 Encontrado: landzone/fornecedores_db1.parquet
✅ Arquivo landzone/fornecedores_db1.parquet baixado para minio_downloads/fornecedores_db1.parquet
⚠️ Arquivo landzone/fornecedores_db1.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/fornecedores_db2.parquet
✅ Arquivo landzone/fornecedores_db2.parquet baixado para minio_downloads/fornecedores_db2.parquet
⚠️ Arquivo landzone/fornecedores_db2.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/fornecedores_db3.parquet
✅ Arquivo landzone/fornecedores_db3.parquet baixado para minio_downloads/fornecedores_db3.parquet
⚠️ Arquivo landzone/fornecedores_db3.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/produtos_db1.parquet
✅ Arquivo landzone/produtos_db1.parquet baixado para minio_downloads/produtos_db1.parquet
⚠️ Arquivo landzone/produtos_db1.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/produtos_db2.parquet
✅ Arquivo landzone/produtos_db2.parquet baixado para minio_downloads/produtos_db2.parquet
⚠️ Arquivo landzone/produtos_db2.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/produtos_db3.parquet
✅ Arquivo landzone/produtos_db3.parquet baixado para minio_downloads/produtos_db3.parquet
⚠️ Arquivo landzone/produtos_db3.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendas_db1.parquet
✅ Arquivo landzone/vendas_db1.parquet baixado para minio_downloads/vendas_db1.parquet
⚠️ Arquivo landzone/vendas_db1.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendas_db2.parquet
✅ Arquivo landzone/vendas_db2.parquet baixado para minio_downloads/vendas_db2.parquet
⚠️ Arquivo landzone/vendas_db2.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendas_db3.parquet
✅ Arquivo landzone/vendas_db3.parquet baixado para minio_downloads/vendas_db3.parquet
⚠️ Arquivo landzone/vendas_db3.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendedores_db1.parquet
✅ Arquivo landzone/vendedores_db1.parquet baixado para minio_downloads/vendedores_db1.parquet
⚠️ Arquivo landzone/vendedores_db1.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendedores_db2.parquet
✅ Arquivo landzone/vendedores_db2.parquet baixado para minio_downloads/vendedores_db2.parquet
⚠️ Arquivo landzone/vendedores_db2.parquet ignorado (sem correspondência de schema).
📂 Encontrado: landzone/vendedores_db3.parquet
✅ Arquivo landzone/vendedores_db3.parquet baixado para minio_downloads/vendedores_db3.parquet
⚠️ Arquivo landzone/vendedores_db3.parquet ignorado (sem correspondência de schema).

🔍 Listando arquivos no bucket 'datalake' com prefixo 'bronze/'...
📂 Encontrado: bronze/bronzedb1/fornecedores.parquet
✅ Arquivo bronze/bronzedb1/fornecedores.parquet baixado para minio_downloads/fornecedores.parquet
📊 Criando tabela: bronzedb1.fornecedores
✅ Arquivo bronze/bronzedb1/fornecedores.parquet carregado no schema bronzedb1 como fornecedores
📂 Encontrado: bronze/bronzedb1/produtos.parquet
✅ Arquivo bronze/bronzedb1/produtos.parquet baixado para minio_downloads/produtos.parquet
📊 Criando tabela: bronzedb1.produtos
✅ Arquivo bronze/bronzedb1/produtos.parquet carregado no schema bronzedb1 como produtos
📂 Encontrado: bronze/bronzedb1/vendas.parquet
✅ Arquivo bronze/bronzedb1/vendas.parquet baixado para minio_downloads/vendas.parquet
📊 Criando tabela: bronzedb1.vendas
✅ Arquivo bronze/bronzedb1/vendas.parquet carregado no schema bronzedb1 como vendas
📂 Encontrado: bronze/bronzedb1/vendedores.parquet
✅ Arquivo bronze/bronzedb1/vendedores.parquet baixado para minio_downloads/vendedores.parquet
📊 Criando tabela: bronzedb1.vendedores
✅ Arquivo bronze/bronzedb1/vendedores.parquet carregado no schema bronzedb1 como vendedores
📂 Encontrado: bronze/bronzedb2/fornecedores.parquet
✅ Arquivo bronze/bronzedb2/fornecedores.parquet baixado para minio_downloads/fornecedores.parquet
📊 Criando tabela: bronzedb2.fornecedores
✅ Arquivo bronze/bronzedb2/fornecedores.parquet carregado no schema bronzedb2 como fornecedores
📂 Encontrado: bronze/bronzedb2/produtos.parquet

✅ Arquivo bronze/bronzedb2/produtos.parquet baixado para minio_downloads/produtos.parquet
📊 Criando tabela: bronzedb2.produtos
✅ Arquivo bronze/bronzedb2/produtos.parquet carregado no schema bronzedb2 como produtos
📂 Encontrado: bronze/bronzedb2/vendas.parquet
✅ Arquivo bronze/bronzedb2/vendas.parquet baixado para minio_downloads/vendas.parquet
📊 Criando tabela: bronzedb2.vendas
✅ Arquivo bronze/bronzedb2/vendas.parquet carregado no schema bronzedb2 como vendas
📂 Encontrado: bronze/bronzedb2/vendedores.parquet
✅ Arquivo bronze/bronzedb2/vendedores.parquet baixado para minio_downloads/vendedores.parquet
📊 Criando tabela: bronzedb2.vendedores
✅ Arquivo bronze/bronzedb2/vendedores.parquet carregado no schema bronzedb2 como vendedores
📂 Encontrado: bronze/bronzedb3/fornecedores.parquet
✅ Arquivo bronze/bronzedb3/fornecedores.parquet baixado para minio_downloads/fornecedores.parquet
📊 Criando tabela: bronzedb3.fornecedores
✅ Arquivo bronze/bronzedb3/fornecedores.parquet carregado no schema bronzedb3 como fornecedores
📂 Encontrado: bronze/bronzedb3/produtos.parquet
✅ Arquivo bronze/bronzedb3/produtos.parquet baixado para minio_downloads/produtos.parquet
📊 Criando tabela: bronzedb3.produtos
✅ Arquivo bronze/bronzedb3/produtos.parquet carregado no schema bronzedb3 como produtos
📂 Encontrado: bronze/bronzedb3/vendas.parquet
✅ Arquivo bronze/bronzedb3/vendas.parquet baixado para minio_downloads/vendas.parquet
📊 Criando tabela: bronzedb3.vendas
✅ Arquivo bronze/bronzedb3/vendas.parquet carregado no schema bronzedb3 como vendas
📂 Encontrado: bronze/bronzedb3/vendedores.parquet
✅ Arquivo bronze/bronzedb3/vendedores.parquet baixado para minio_downloads/vendedores.parquet
📊 Criando tabela: bronzedb3.vendedores
✅ Arquivo bronze/bronzedb3/vendedores.parquet carregado no schema bronzedb3 como vendedores

🎉 Processo concluído!

In [19]:
import duckdb
import pandas as pd
from minio import Minio
import os

# Configuração do MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Buckets e caminhos das camadas
bucket = "datalake"
bucketZone = "landzone"
landzone_prefix = "landzone/"
bronze_prefix = "bronze/"

# Conectar ao DuckDB
conn = duckdb.connect()

# Configuração do MinIO no DuckDB para leitura S3
conn.execute("SET s3_access_key_id='minioadmin';")
conn.execute("SET s3_secret_access_key='minioadmin';")
conn.execute("SET s3_endpoint='127.0.0.1:9001';")
conn.execute("SET s3_use_ssl=false;")

# Listar arquivos da camada Landzone
objects = minio_client.list_objects(bucketZone, prefix=landzone_prefix, recursive=True)
arquivos_landzone = [obj.object_name for obj in objects if obj.object_name.endswith(".parquet")]

# Exibir os arquivos encontrados na landzone
print("\n📂 Arquivos encontrados na landzone:")
print("\n".join(arquivos_landzone) if arquivos_landzone else "⚠️ Nenhum arquivo encontrado!")

if not arquivos_landzone:
    exit("🚨 ERRO: Nenhum arquivo Parquet encontrado na camada landzone!")

# Percorrer cada arquivo na landzone
for arquivo in arquivos_landzone:
    nome_tabela = arquivo.split("/")[-1]  # Nome do arquivo
    bronze_path = bronze_prefix + nome_tabela  # Caminho na Bronze

    print(f"\n🔍 Processando arquivo: {arquivo}")
    
    # Ler os dados da Landzone com a sintaxe correta
    try:
        df_landzone = conn.execute(
            f"SELECT * FROM read_parquet('s3://{bucket}/{arquivo}')"
        ).fetchdf()

        print(f"✅ Dados carregados de {arquivo} ({len(df_landzone)} linhas).")
        print(df_landzone.head())
        
        if df_landzone.empty:
            print(f"⚠️ O arquivo {arquivo} está vazio! Pulando para o próximo.")
            continue

    except Exception as e:
        print(f"❌ ERRO ao ler {arquivo} da landzone: {e}")
        continue

    # Verificar se o arquivo já existe na Bronze
    try:
        minio_client.stat_object(bucket, bronze_path)
        bronze_existe = True
        print(f"📦 Arquivo {bronze_path} já existe na Bronze.")
    except Exception:
        bronze_existe = False
        print(f"⚠️ Arquivo {bronze_path} NÃO encontrado na Bronze. Será criado.")

    # Definir chave primária (ajuste conforme necessário)
    primary_keys = ["id"]  # Modifique conforme o esquema das suas tabelas

    if bronze_existe:
        # Ler os dados da Bronze
        try:
            df_bronze = conn.execute(
                f"SELECT * FROM read_parquet('s3://{bucket}/{bronze_path}')"
            ).fetchdf()

            print(f"📊 Dados carregados da Bronze ({len(df_bronze)} linhas).")

        except Exception as e:
            print(f"❌ ERRO ao ler {bronze_path}: {e}")
            continue

        # Criar DataFrames indexados para comparação
        lz = df_landzone.set_index(primary_keys)
        bz = df_bronze.set_index(primary_keys)

        # Identificar novas linhas
        novas_linhas = lz.loc[~lz.index.isin(bz.index)].reset_index()

        # Identificar linhas alteradas
        dados_diferentes = lz.loc[lz.index.isin(bz.index) & (lz != bz).any(axis=1)].reset_index()

        print(f"📌 Novas linhas: {len(novas_linhas)} | Linhas alteradas: {len(dados_diferentes)}")

        if not novas_linhas.empty or not dados_diferentes.empty:
            # Criar novo dataframe combinando dados novos e atualizados
            final_df = duckdb.sql("SELECT * FROM df_bronze EXCEPT SELECT * FROM df_landzone")
            final_df = final_df.union(novas_linhas).union(dados_diferentes)

            print(f"📥 Atualizando Bronze com {len(final_df)} registros...")

            # Salvar o arquivo temporário antes de enviar ao MinIO
            temp_path = f"/tmp/{nome_tabela}"
            final_df.to_parquet(temp_path)
            print(f"📥 Arquivo temporário salvo em {temp_path}")

            # Enviar para o MinIO
            with open(temp_path, "rb") as file_data:
                try:
                    minio_client.put_object(bucket, bronze_path, file_data, length=-1, part_size=10*1024*1024)
                    print(f"🚀 Bronze atualizado: {bronze_path}")
                except Exception as e:
                    print(f"❌ Erro ao enviar {bronze_path} para MinIO: {e}")

    else:
        # Criar nova tabela na Bronze
        temp_path = f"/tmp/{nome_tabela}"
        print(f"🆕 Criando nova tabela Bronze: {bronze_path}")

        df_landzone.to_parquet(temp_path)
        print(f"📥 Arquivo temporário salvo em {temp_path}")

        # Enviar para o MinIO
        with open(temp_path, "rb") as file_data:
            try:
                minio_client.put_object(bucket, bronze_path, file_data, length=-1, part_size=10*1024*1024)
                print(f"✅ Tabela {bronze_path} criada na Bronze!")
            except Exception as e:
                print(f"❌ Erro ao criar {bronze_path} na Bronze: {e}")

print("\n✅ Processo concluído!")

📂 Arquivos encontrados na landzone:
landzone/fornecedores_db1.parquet
landzone/fornecedores_db2.parquet
landzone/fornecedores_db3.parquet
landzone/produtos_db1.parquet
landzone/produtos_db2.parquet
landzone/produtos_db3.parquet
landzone/vendas_db1.parquet
landzone/vendas_db2.parquet
landzone/vendas_db3.parquet
landzone/vendedores_db1.parquet
landzone/vendedores_db2.parquet
landzone/vendedores_db3.parquet

🔍 Processando arquivo: landzone/fornecedores_db1.parquet
❌ ERRO ao ler landzone/fornecedores_db1.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/fornecedores_db1.parquet'

🔍 Processando arquivo: landzone/fornecedores_db2.parquet
❌ ERRO ao ler landzone/fornecedores_db2.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/fornecedores_db2.parquet'

🔍 Processando arquivo: landzone/fornecedores_db3.parquet
❌ ERRO ao ler landzone/fornecedores_db3.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/fornecedores_db3.parquet'

🔍 Processando arquivo: landzone/produtos_db1.parquet
❌ ERRO ao ler landzone/produtos_db1.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/produtos_db1.parquet'

🔍 Processando arquivo: landzone/produtos_db2.parquet
❌ ERRO ao ler landzone/produtos_db2.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/produtos_db2.parquet'

🔍 Processando arquivo: landzone/produtos_db3.parquet
❌ ERRO ao ler landzone/produtos_db3.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/produtos_db3.parquet'

🔍 Processando arquivo: landzone/vendas_db1.parquet
❌ ERRO ao ler landzone/vendas_db1.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendas_db1.parquet'

🔍 Processando arquivo: landzone/vendas_db2.parquet
❌ ERRO ao ler landzone/vendas_db2.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendas_db2.parquet'

🔍 Processando arquivo: landzone/vendas_db3.parquet
❌ ERRO ao ler landzone/vendas_db3.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendas_db3.parquet'

🔍 Processando arquivo: landzone/vendedores_db1.parquet
❌ ERRO ao ler landzone/vendedores_db1.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendedores_db1.parquet'

🔍 Processando arquivo: landzone/vendedores_db2.parquet
❌ ERRO ao ler landzone/vendedores_db2.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendedores_db2.parquet'

🔍 Processando arquivo: landzone/vendedores_db3.parquet
❌ ERRO ao ler landzone/vendedores_db3.parquet da landzone: IO Error: Could not establish connection error for HTTP HEAD to 'http://datalake.127.0.0.1:9001/landzone/vendedores_db3.parquet'

✅ Processo concluído!

In [24]:
from minio import Minio
import duckdb

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nome do bucket e do arquivo Parquet
bucket_name = "landzone"
parquet_file = "landzone/fornecedores_db1.parquet"
local_file = "fornecedores_db1.parquet"

# Baixar o arquivo Parquet do MinIO para o sistema local
minio_client.fget_object(bucket_name, parquet_file, local_file)

# Conectar ao DuckDB e realizar a consulta
conn = duckdb.connect()

# Consulta SQL para ler o arquivo Parquet local
query = f"SELECT * FROM read_parquet('{local_file}')"

# Executar a consulta e obter os resultados
result = conn.execute(query).fetchall()

# Exibir os resultados
for row in result:
    print(row)

# Fechar a conexão
conn.close()

(1, 'Machado - ME', 'Estrada de Azevedo\nVila Nova\n33390-723 da Mota / AL', '+55 81 5040-7669', '2025-02-05 07:11:41', 'db1')
(2, 'Melo Martins Ltda.', 'Passarela de Cardoso, 71\nVila Betânia\n38705-724 Rodrigues do Norte / SE', '0500 859 7457', '2025-02-05 07:11:41', 'db1')
(3, 'Pereira - EI', 'Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n85015006 Barros do Campo / MA', '(011) 8144-8050', '2025-02-05 07:11:41', 'db1')
(4, 'Casa Grande', 'Distrito Julia Pastor, 9\nEstrela Do Oriente\n41670244 Gonçalves / RO', '(041) 3565-8571', '2025-02-05 07:11:41', 'db1')
(5, 'Sales', 'Chácara de Pires, 9\nPindura Saia\n00870394 Pires da Prata / RS', '(084) 2173-5590', '2025-02-05 07:11:41', 'db1')
(6, 'Abreu', 'Feira Nicolas Dias, 22\nGameleira\n00329079 da Cunha / AL', '+55 71 3187-2758', '2025-02-05 07:11:41', 'db1')
(7, 'Ribeiro', 'Praia de da Mata, 8\nJoão Alfredo\n98866-706 Freitas de Santos / MG', '84 9622 9908', '2025-02-05 07:11:41', 'db1')
(8, 'Costa Mendonça e Filhos', 'Travessa Barros, 802\nCinquentenário\n45486-423 Cassiano de Pires / PI', '0500 509 3592', '2025-02-05 07:11:41', 'db1')
(9, 'Ribeiro', 'Vale de Fogaça, 65\nAlto Dos Pinheiros\n25866076 Moraes de Rios / AC', '71 9829-4069', '2025-02-05 07:11:41', 'db1')
(10, 'Carvalho S.A.', 'Colônia de Jesus, 14\nConjunto Taquaril\n62597473 Rocha de Minas / AC', '+55 61 4893-9602', '2025-02-05 07:11:41', 'db1')
(11, 'Nunes', 'Condomínio Almeida\nCidade Jardim\n47696-418 Viana de da Cunha / PE', '+55 51 8469 7227', '2025-02-05 07:11:41', 'db1')
(12, 'Viana Pereira S/A', 'Estação Luiz Fernando da Rocha, 457\nJardim Atlântico\n08499-981 Alves / TO', '31 4137-3148', '2025-02-05 07:11:41', 'db1')
(13, 'Cavalcante', 'Rua de Siqueira, 36\nMinas Brasil\n72670397 Correia / MG', '+55 21 7247-8470', '2025-02-05 07:11:41', 'db1')
(14, 'Pinto Novais S/A', 'Loteamento de Camargo, 53\nGraça\n28553492 Campos / SP', '+55 (071) 0022-0612', '2025-02-05 07:11:41', 'db1')
(15, 'da Rocha Ltda.', 'Morro Castro, 68\nSão Jorge 3ª Seção\n88148889 da Paz / ES', '51 8478 8592', '2025-02-05 07:11:41', 'db1')
(16, 'Sá', 'Largo João Cirino, 644\nSaudade\n37173-020 Porto / AL', '(061) 0761 7014', '2025-02-05 07:11:41', 'db1')
(17, 'da Cunha Sousa e Filhos', 'Via de Aparecida\nSanta Isabel\n47163-670 Cassiano da Prata / RJ', '+55 61 1689 8303', '2025-02-05 07:11:41', 'db1')
(18, 'Farias - ME', 'Núcleo Lunna Freitas, 26\nVila Nova Cachoeirinha 2ª Seção\n74911464 Costa Paulista / SP', '+55 51 3839 2286', '2025-02-05 07:11:41', 'db1')
(19, 'Rios - ME', 'Rodovia Asafe Cavalcanti\nComiteco\n10407897 Brito / BA', '+55 61 2295 0105', '2025-02-05 07:11:41', 'db1')
(20, 'Macedo', 'Via Freitas, 241\nAlto Das Antenas\n21448085 Farias Paulista / RN', '21 2997 8905', '2025-02-05 07:11:41', 'db1')
(21, 'das Neves S.A.', 'Avenida Isis Aparecida\nEstoril\n36007629 Abreu / BA', '0900 823 7906', '2025-02-05 07:11:41', 'db1')
(22, 'Moreira', 'Favela de Casa Grande, 83\nTres Marias\n17438261 Carvalho de Lima / SP', '+55 11 2443-4792', '2025-02-05 07:11:41', 'db1')
(23, 'Fonseca', 'Pátio Vargas, 18\nMala E Cuia\n69300419 Nogueira / MG', '(051) 2570 4520', '2025-02-05 07:11:41', 'db1')
(1, 'Machado - ME', 'Estrada de Azevedo\nVila Nova\n33390-723 da Mota / AL', '+55 81 5040-7669', '2025-02-05 07:11:41', 'db1')
(2, 'Melo Martins Ltda.', 'Passarela de Cardoso, 71\nVila Betânia\n38705-724 Rodrigues do Norte / SE', '0500 859 7457', '2025-02-05 07:11:41', 'db1')
(3, 'Pereira - EI', 'Recanto Lorenzo Pacheco, 18\nCapitão Eduardo\n85015006 Barros do Campo / MA', '(011) 8144-8050', '2025-02-05 07:11:41', 'db1')
(4, 'Casa Grande', 'Distrito Julia Pastor, 9\nEstrela Do Oriente\n41670244 Gonçalves / RO', '(041) 3565-8571', '2025-02-05 07:11:41', 'db1')
(5, 'Sales', 'Chácara de Pires, 9\nPindura Saia\n00870394 Pires da Prata / RS', '(084) 2173-5590', '2025-02-05 07:11:41', 'db1')
(6, 'Abreu', 'Feira Nicolas Dias, 22\nGameleira\n00329079 da Cunha / AL', '+55 71 3187-2758', '2025-02-05 07:11:41', 'db1')
(7, 'Ribeiro', 'Praia de da Mata, 8\nJoão Alfredo\n98866-706 Freitas de Santos / MG', '84 9622 9908', '2025-02-05 07:11:41', 'db1')
(8, 'Costa Mendonça e Filhos', 'Travessa Barros, 802\nCinquentenário\n45486-423 Cassiano de Pires / PI', '0500 509 3592', '2025-02-05 07:11:41', 'db1')
(9, 'Ribeiro', 'Vale de Fogaça, 65\nAlto Dos Pinheiros\n25866076 Moraes de Rios / AC', '71 9829-4069', '2025-02-05 07:11:41', 'db1')
(10, 'Carvalho S.A.', 'Colônia de Jesus, 14\nConjunto Taquaril\n62597473 Rocha de Minas / AC', '+55 61 4893-9602', '2025-02-05 07:11:41', 'db1')
(11, 'Nunes', 'Condomínio Almeida\nCidade Jardim\n47696-418 Viana de da Cunha / PE', '+55 51 8469 7227', '2025-02-05 07:11:41', 'db1')
(12, 'Viana Pereira S/A', 'Estação Luiz Fernando da Rocha, 457\nJardim Atlântico\n08499-981 Alves / TO', '31 4137-3148', '2025-02-05 07:11:41', 'db1')
(13, 'Cavalcante', 'Rua de Siqueira, 36\nMinas Brasil\n72670397 Correia / MG', '+55 21 7247-8470', '2025-02-05 07:11:41', 'db1')
(14, 'Pinto Novais S/A', 'Loteamento de Camargo, 53\nGraça\n28553492 Campos / SP', '+55 (071) 0022-0612', '2025-02-05 07:11:41', 'db1')
(15, 'da Rocha Ltda.', 'Morro Castro, 68\nSão Jorge 3ª Seção\n88148889 da Paz / ES', '51 8478 8592', '2025-02-05 07:11:41', 'db1')
(16, 'Sá', 'Largo João Cirino, 644\nSaudade\n37173-020 Porto / AL', '(061) 0761 7014', '2025-02-05 07:11:41', 'db1')
(17, 'da Cunha Sousa e Filhos', 'Via de Aparecida\nSanta Isabel\n47163-670 Cassiano da Prata / RJ', '+55 61 1689 8303', '2025-02-05 07:11:41', 'db1')
(18, 'Farias - ME', 'Núcleo Lunna Freitas, 26\nVila Nova Cachoeirinha 2ª Seção\n74911464 Costa Paulista / SP', '+55 51 3839 2286', '2025-02-05 07:11:41', 'db1')
(19, 'Rios - ME', 'Rodovia Asafe Cavalcanti\nComiteco\n10407897 Brito / BA', '+55 61 2295 0105', '2025-02-05 07:11:41', 'db1')
(20, 'Macedo', 'Via Freitas, 241\nAlto Das Antenas\n21448085 Farias Paulista / RN', '21 2997 8905', '2025-02-05 07:11:41', 'db1')
(21, 'das Neves S.A.', 'Avenida Isis Aparecida\nEstoril\n36007629 Abreu / BA', '0900 823 7906', '2025-02-05 07:11:41', 'db1')
(22, 'Moreira', 'Favela de Casa Grande, 83\nTres Marias\n17438261 Carvalho de Lima / SP', '+55 11 2443-4792', '2025-02-05 07:11:41', 'db1')
(23, 'Fonseca', 'Pátio Vargas, 18\nMala E Cuia\n69300419 Nogueira / MG', '(051) 2570 4520', '2025-02-05 07:11:41', 'db1')

In [27]:
from minio import Minio
from minio.error import S3Error
from minio.commonconfig import CopySource  # Importação necessária

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para verificar se um bucket existe
def bucket_exists(bucket_name):
    try:
        return minio_client.bucket_exists(bucket_name)
    except S3Error:
        return False

# Função para criar um bucket se ele não existir
def create_bucket_if_not_exists(bucket_name):
    if not bucket_exists(bucket_name):
        minio_client.make_bucket(bucket_name)
        print(f"Bucket '{bucket_name}' criado com sucesso.")
    else:
        print(f"Bucket '{bucket_name}' já existe.")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para copiar arquivos entre buckets
def copy_file(source_bucket, source_file, destination_bucket, destination_file):
    try:
        # Define a origem da cópia usando CopySource
        copy_source = CopySource(source_bucket, source_file)

        # Copia o arquivo
        minio_client.copy_object(
            destination_bucket,
            destination_file,
            copy_source
        )
        print(f"Arquivo '{source_file}' copiado para '{destination_bucket}/{destination_file}'.")
    except S3Error as e:
        print(f"Erro ao copiar arquivo '{source_file}': {e}")

# Verifica se o bucket 'datalake' existe ou cria ele
create_bucket_if_not_exists(bronze_bucket)

# Lista todos os arquivos na 'landzone'
landzone_files = list_files(landzone_bucket)

# Processa cada arquivo na 'landzone'
for file_path in landzone_files:
    # Extrai o nome do arquivo (ex: fornecedores_db1.parquet)
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: fornecedores_db1.parquet)
    if file_name.startswith("fornecedores_db") and file_name.endswith(".parquet"):
        # Extrai o número do banco (ex: db1, db2, db3)
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Define o caminho de destino no bucket 'datalake/bronze'
        destination_path = f"bronze/{db_number}/{file_name}"

        # Copia o arquivo para o destino
        copy_file(landzone_bucket, file_path, bronze_bucket, destination_path)

Bucket 'datalake' já existe.
Arquivo 'landzone/fornecedores_db1.parquet' copiado para 'datalake/bronze/db1/fornecedores_db1.parquet'.
Arquivo 'landzone/fornecedores_db2.parquet' copiado para 'datalake/bronze/db2/fornecedores_db2.parquet'.
Arquivo 'landzone/fornecedores_db3.parquet' copiado para 'datalake/bronze/db3/fornecedores_db3.parquet'.

In [28]:
from minio import Minio
from minio.error import S3Error
from minio.commonconfig import CopySource

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para verificar se um bucket existe
def bucket_exists(bucket_name):
    try:
        return minio_client.bucket_exists(bucket_name)
    except S3Error:
        return False

# Função para criar um bucket se ele não existir
def create_bucket_if_not_exists(bucket_name):
    if not bucket_exists(bucket_name):
        minio_client.make_bucket(bucket_name)
        print(f"Bucket '{bucket_name}' criado com sucesso.")
    else:
        print(f"Bucket '{bucket_name}' já existe.")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para copiar arquivos entre buckets
def copy_file(source_bucket, source_file, destination_bucket, destination_file):
    try:
        # Define a origem da cópia usando CopySource
        copy_source = CopySource(source_bucket, source_file)

        # Copia o arquivo
        minio_client.copy_object(
            destination_bucket,
            destination_file,
            copy_source
        )
        print(f"Arquivo '{source_file}' copiado para '{destination_bucket}/{destination_file}'.")
    except S3Error as e:
        print(f"Erro ao copiar arquivo '{source_file}': {e}")

# Verifica se o bucket 'datalake' existe ou cria ele
create_bucket_if_not_exists(bronze_bucket)

# Lista todos os arquivos na 'landzone'
landzone_files = list_files(landzone_bucket)

# Processa cada arquivo na 'landzone'
for file_path in landzone_files:
    # Extrai o nome do arquivo (ex: fornecedores_db1.parquet)
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_name and file_name.endswith(".parquet"):
        # Extrai o tipo do arquivo (ex: fornecedores, clientes, produtos)
        file_type = file_name.split("_db")[0]

        # Extrai o número do banco (ex: db1, db2, db3)
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Define o caminho de destino no bucket 'datalake/bronze'
        destination_path = f"bronze/{db_number}/{file_type}/{file_name}"

        # Copia o arquivo para o destino
        copy_file(landzone_bucket, file_path, bronze_bucket, destination_path)

Bucket 'datalake' já existe.
Arquivo 'landzone/fornecedores_db1.parquet' copiado para 'datalake/bronze/db1/fornecedores/fornecedores_db1.parquet'.
Arquivo 'landzone/fornecedores_db2.parquet' copiado para 'datalake/bronze/db2/fornecedores/fornecedores_db2.parquet'.
Arquivo 'landzone/fornecedores_db3.parquet' copiado para 'datalake/bronze/db3/fornecedores/fornecedores_db3.parquet'.
Arquivo 'landzone/produtos_db1.parquet' copiado para 'datalake/bronze/db1/produtos/produtos_db1.parquet'.
Arquivo 'landzone/produtos_db2.parquet' copiado para 'datalake/bronze/db2/produtos/produtos_db2.parquet'.
Arquivo 'landzone/produtos_db3.parquet' copiado para 'datalake/bronze/db3/produtos/produtos_db3.parquet'.
Arquivo 'landzone/vendas_db1.parquet' copiado para 'datalake/bronze/db1/vendas/vendas_db1.parquet'.
Arquivo 'landzone/vendas_db2.parquet' copiado para 'datalake/bronze/db2/vendas/vendas_db2.parquet'.
Arquivo 'landzone/vendas_db3.parquet' copiado para 'datalake/bronze/db3/vendas/vendas_db3.parquet'.
Arquivo 'landzone/vendedores_db1.parquet' copiado para 'datalake/bronze/db1/vendedores/vendedores_db1.parquet'.
Arquivo 'landzone/vendedores_db2.parquet' copiado para 'datalake/bronze/db2/vendedores/vendedores_db2.parquet'.
Arquivo 'landzone/vendedores_db3.parquet' copiado para 'datalake/bronze/db3/vendedores/vendedores_db3.parquet'.

In [29]:
from minio import Minio
from minio.error import S3Error
from minio.commonconfig import CopySource
from datetime import datetime

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para verificar se um bucket existe
def bucket_exists(bucket_name):
    try:
        return minio_client.bucket_exists(bucket_name)
    except S3Error:
        return False

# Função para criar um bucket se ele não existir
def create_bucket_if_not_exists(bucket_name):
    if not bucket_exists(bucket_name):
        minio_client.make_bucket(bucket_name)
        print(f"Bucket '{bucket_name}' criado com sucesso.")
    else:
        print(f"Bucket '{bucket_name}' já existe.")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return {obj.object_name: obj.last_modified for obj in objects}
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return {}

# Função para copiar arquivos entre buckets
def copy_file(source_bucket, source_file, destination_bucket, destination_file):
    try:
        # Define a origem da cópia usando CopySource
        copy_source = CopySource(source_bucket, source_file)

        # Copia o arquivo
        minio_client.copy_object(
            destination_bucket,
            destination_file,
            copy_source
        )
        print(f"Arquivo '{source_file}' copiado para '{destination_bucket}/{destination_file}'.")
    except S3Error as e:
        print(f"Erro ao copiar arquivo '{source_file}': {e}")

# Verifica se o bucket 'datalake' existe ou cria ele
create_bucket_if_not_exists(bronze_bucket)

# Lista todos os arquivos na 'landzone' e na 'bronze' com seus timestamps
landzone_files = list_files(landzone_bucket)
bronze_files = list_files(bronze_bucket)

# Processa cada arquivo na 'landzone'
for file_path, landzone_timestamp in landzone_files.items():
    # Extrai o nome do arquivo (ex: fornecedores_db1.parquet)
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_name and file_name.endswith(".parquet"):
        # Extrai o tipo do arquivo (ex: fornecedores, clientes, produtos)
        file_type = file_name.split("_db")[0]

        # Extrai o número do banco (ex: db1, db2, db3)
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Define o caminho de destino no bucket 'datalake/bronze'
        destination_path = f"bronze/{db_number}/{file_type}/{file_name}"

        # Verifica se o arquivo já existe na 'bronze'
        if destination_path in bronze_files:
            # Compara os timestamps de modificação
            bronze_timestamp = bronze_files[destination_path]
            if landzone_timestamp > bronze_timestamp:
                # Se o arquivo na 'landzone' for mais recente, faz o upsert
                print(f"Arquivo '{file_name}' na 'landzone' é mais recente. Atualizando na 'bronze'...")
                copy_file(landzone_bucket, file_path, bronze_bucket, destination_path)
            else:
                print(f"Arquivo '{file_name}' na 'bronze' já está atualizado.")
        else:
            # Se o arquivo não existir na 'bronze', faz a cópia
            print(f"Arquivo '{file_name}' não existe na 'bronze'. Inserindo...")
            copy_file(landzone_bucket, file_path, bronze_bucket, destination_path)

Bucket 'datalake' já existe.
Arquivo 'fornecedores_db1.parquet' na 'bronze' já está atualizado.
Arquivo 'fornecedores_db2.parquet' na 'bronze' já está atualizado.
Arquivo 'fornecedores_db3.parquet' na 'bronze' já está atualizado.
Arquivo 'produtos_db1.parquet' na 'bronze' já está atualizado.
Arquivo 'produtos_db2.parquet' na 'bronze' já está atualizado.
Arquivo 'produtos_db3.parquet' na 'bronze' já está atualizado.
Arquivo 'vendas_db1.parquet' na 'bronze' já está atualizado.
Arquivo 'vendas_db2.parquet' na 'bronze' já está atualizado.
Arquivo 'vendas_db3.parquet' na 'bronze' já está atualizado.
Arquivo 'vendedores_db1.parquet' na 'bronze' já está atualizado.
Arquivo 'vendedores_db2.parquet' na 'bronze' já está atualizado.
Arquivo 'vendedores_db3.parquet' na 'bronze' já está atualizado.

In [29]:
from minio import Minio
from minio.error import S3Error
import duckdb
import os

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para baixar um arquivo do MinIO para o sistema local
def download_file(bucket_name, file_path, local_path):
    try:
        minio_client.fget_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{file_path}' baixado para '{local_path}'.")
    except S3Error as e:
        print(f"Erro ao baixar o arquivo '{file_path}': {e}")

# Função para fazer upload de um arquivo para o MinIO
def upload_file(bucket_name, file_path, local_path):
    try:
        minio_client.fput_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{local_path}' enviado para '{bucket_name}/{file_path}'.")
    except S3Error as e:
        print(f"Erro ao enviar o arquivo '{local_path}': {e}")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para realizar o upsert usando DuckDB
def upsert_parquet(landzone_file, bronze_file, output_file):
    # Conectar ao DuckDB
    conn = duckdb.connect()

    # Ler os arquivos Parquet
    landzone_df = conn.execute(f"SELECT * FROM read_parquet('{landzone_file}')").fetchdf()
    bronze_df = conn.execute(f"SELECT * FROM read_parquet('{bronze_file}')").fetchdf()

    # Supondo que há uma coluna única para identificar registros (ex: id)
    primary_key = "id"  # Altere para a coluna correta

    # Realizar o upsert
    upsert_query = f"""
    SELECT * FROM landzone_df
    UNION ALL
    SELECT * FROM bronze_df
    WHERE {primary_key} NOT IN (SELECT {primary_key} FROM landzone_df)
    """
    result_df = conn.execute(upsert_query).fetchdf()

    # Salvar o resultado em um novo arquivo Parquet
    result_df.to_parquet(output_file)
    print(f"Upsert concluído. Resultado salvo em '{output_file}'.")

    # Fechar a conexão
    conn.close()

# Verifica se o bucket 'datalake' existe ou cria ele
if not minio_client.bucket_exists(bronze_bucket):
    minio_client.make_bucket(bronze_bucket)
    print(f"Bucket '{bronze_bucket}' criado com sucesso.")

# Lista todos os arquivos na 'landzone'
landzone_files = list_files(landzone_bucket)

# Processa cada arquivo na 'landzone'
for file_path in landzone_files:
    # Extrai o nome do arquivo (ex: fornecedores_db1.parquet)
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_name and file_name.endswith(".parquet"):
        # Extrai o tipo do arquivo (ex: fornecedores, clientes, produtos)
        file_type = file_name.split("_db")[0]

        # Extrai o número do banco (ex: db1, db2, db3)
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Define o caminho de destino no bucket 'datalake/bronze'
        destination_path = f"bronze/{db_number}/{file_type}/{file_name}"

        # Baixa os arquivos da 'landzone' e da 'bronze' para o sistema local
        local_landzone_file = f"temp_landzone_{file_name}"
        local_bronze_file = f"temp_bronze_{file_name}"
        local_output_file = f"temp_output_{file_name}"

        download_file(landzone_bucket, file_path, local_landzone_file)
        if minio_client.stat_object(bronze_bucket, destination_path):
            download_file(bronze_bucket, destination_path, local_bronze_file)
        else:
            local_bronze_file = None  # Arquivo não existe na 'bronze'

        # Realiza o upsert
        if local_bronze_file:
            upsert_parquet(local_landzone_file, local_bronze_file, local_output_file)
        else:
            # Se o arquivo não existir na 'bronze', apenas copia o arquivo da 'landzone'
            print(f"Arquivo '{file_name}' não existe na 'bronze'. Inserindo...")
            upload_file(bronze_bucket, destination_path, local_landzone_file)

        # Remove os arquivos temporários
        os.remove(local_landzone_file)
        if local_bronze_file:
            os.remove(local_bronze_file)
        if os.path.exists(local_output_file):
            os.remove(local_output_file)

Arquivo 'landzone/fornecedores_db1.parquet' baixado para 'temp_landzone_fornecedores_db1.parquet'.

S3Error: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /datalake/bronze/db1/fornecedores/fornecedores_db1.parquet, request_id: 1821E2200D080F68, host_id: 7987905dee74cdeb212432486a178e511309594cee7cb75f892cd53e35f09ea4, bucket_name: datalake, object_name: bronze/db1/fornecedores/fornecedores_db1.parquet

In [30]:
from minio import Minio
from minio.error import S3Error
import duckdb
import os

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para baixar um arquivo do MinIO para o sistema local
def download_file(bucket_name, file_path, local_path):
    try:
        minio_client.fget_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{file_path}' baixado para '{local_path}'.")
    except S3Error as e:
        print(f"Erro ao baixar o arquivo '{file_path}': {e}")

# Função para fazer upload de um arquivo para o MinIO
def upload_file(bucket_name, file_path, local_path):
    try:
        minio_client.fput_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{local_path}' enviado para '{bucket_name}/{file_path}'.")
    except S3Error as e:
        print(f"Erro ao enviar o arquivo '{local_path}': {e}")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    if not minio_client.bucket_exists(bucket_name):
        print(f"Bucket '{bucket_name}' não existe.")
        return []
    
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para realizar o upsert usando DuckDB
def upsert_parquet(landzone_file, bronze_file, output_file):
    conn = duckdb.connect()

    # Verifica se o arquivo bronze existe
    bronze_exists = os.path.exists(bronze_file)

    # Lê os arquivos Parquet
    landzone_df = conn.execute(f"SELECT * FROM read_parquet('{landzone_file}')").fetchdf()
    if bronze_exists:
        bronze_df = conn.execute(f"SELECT * FROM read_parquet('{bronze_file}')").fetchdf()
    else:
        bronze_df = None

    # Supondo que há uma coluna única para identificar registros (ex: id)
    primary_key = "id"  # Altere para a coluna correta

    if bronze_df is not None:
        upsert_query = f"""
        SELECT * FROM landzone_df
        UNION ALL
        SELECT * FROM bronze_df
        WHERE {primary_key} NOT IN (SELECT {primary_key} FROM landzone_df)
        """
        result_df = conn.execute(upsert_query).fetchdf()
    else:
        result_df = landzone_df  # Apenas insere os novos dados se não houver bronze

    # Salva o resultado em um novo arquivo Parquet
    result_df.to_parquet(output_file)
    print(f"Upsert concluído. Resultado salvo em '{output_file}'.")

    conn.close()

# Verifica se o bucket 'datalake' existe ou cria ele
if not minio_client.bucket_exists(bronze_bucket):
    minio_client.make_bucket(bronze_bucket)
    print(f"Bucket '{bronze_bucket}' criado com sucesso.")

# Lista todos os arquivos na 'landzone'
landzone_files = list_files(landzone_bucket)

# Processa cada arquivo na 'landzone'
for file_path in landzone_files:
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_name and file_name.endswith(".parquet"):
        file_type = file_name.split("_db")[0]
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Caminho no bucket 'bronze'
        destination_path = f"bronze/{db_number}/{file_type}/{file_name}"

        # Arquivos locais temporários
        local_landzone_file = f"temp_landzone_{file_name}"
        local_bronze_file = f"temp_bronze_{file_name}"
        local_output_file = f"temp_output_{file_name}"

        # Baixa o arquivo da 'landzone'
        download_file(landzone_bucket, file_path, local_landzone_file)

        # Verifica se o arquivo existe na 'bronze' antes de tentar baixá-lo
        try:
            minio_client.stat_object(bronze_bucket, destination_path)
            download_file(bronze_bucket, destination_path, local_bronze_file)
            bronze_exists = True
        except S3Error:
            print(f"Arquivo '{destination_path}' não encontrado na bronze. Será inserido diretamente.")
            bronze_exists = False

        # Realiza o upsert
        try:
            if bronze_exists:
                upsert_parquet(local_landzone_file, local_bronze_file, local_output_file)
                upload_file(bronze_bucket, destination_path, local_output_file)
            else:
                upload_file(bronze_bucket, destination_path, local_landzone_file)
        finally:
            # Remove arquivos temporários
            for temp_file in [local_landzone_file, local_bronze_file, local_output_file]:
                if os.path.exists(temp_file):
                    os.remove(temp_file)

Arquivo 'landzone/fornecedores_db1.parquet' baixado para 'temp_landzone_fornecedores_db1.parquet'.
Arquivo 'bronze/db1/fornecedores/fornecedores_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db1.parquet' enviado para 'datalake/bronze/db1/fornecedores/fornecedores_db1.parquet'.
Arquivo 'landzone/fornecedores_db2.parquet' baixado para 'temp_landzone_fornecedores_db2.parquet'.
Arquivo 'bronze/db2/fornecedores/fornecedores_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db2.parquet' enviado para 'datalake/bronze/db2/fornecedores/fornecedores_db2.parquet'.
Arquivo 'landzone/fornecedores_db3.parquet' baixado para 'temp_landzone_fornecedores_db3.parquet'.
Arquivo 'bronze/db3/fornecedores/fornecedores_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db3.parquet' enviado para 'datalake/bronze/db3/fornecedores/fornecedores_db3.parquet'.
Arquivo 'landzone/produtos_db1.parquet' baixado para 'temp_landzone_produtos_db1.parquet'.
Arquivo 'bronze/db1/produtos/produtos_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db1.parquet' enviado para 'datalake/bronze/db1/produtos/produtos_db1.parquet'.
Arquivo 'landzone/produtos_db2.parquet' baixado para 'temp_landzone_produtos_db2.parquet'.
Arquivo 'bronze/db2/produtos/produtos_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db2.parquet' enviado para 'datalake/bronze/db2/produtos/produtos_db2.parquet'.
Arquivo 'landzone/produtos_db3.parquet' baixado para 'temp_landzone_produtos_db3.parquet'.
Arquivo 'bronze/db3/produtos/produtos_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db3.parquet' enviado para 'datalake/bronze/db3/produtos/produtos_db3.parquet'.
Arquivo 'landzone/vendas_db1.parquet' baixado para 'temp_landzone_vendas_db1.parquet'.
Arquivo 'bronze/db1/vendas/vendas_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db1.parquet' enviado para 'datalake/bronze/db1/vendas/vendas_db1.parquet'.
Arquivo 'landzone/vendas_db2.parquet' baixado para 'temp_landzone_vendas_db2.parquet'.
Arquivo 'bronze/db2/vendas/vendas_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db2.parquet' enviado para 'datalake/bronze/db2/vendas/vendas_db2.parquet'.
Arquivo 'landzone/vendas_db3.parquet' baixado para 'temp_landzone_vendas_db3.parquet'.
Arquivo 'bronze/db3/vendas/vendas_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db3.parquet' enviado para 'datalake/bronze/db3/vendas/vendas_db3.parquet'.
Arquivo 'landzone/vendedores_db1.parquet' baixado para 'temp_landzone_vendedores_db1.parquet'.
Arquivo 'bronze/db1/vendedores/vendedores_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db1.parquet' enviado para 'datalake/bronze/db1/vendedores/vendedores_db1.parquet'.
Arquivo 'landzone/vendedores_db2.parquet' baixado para 'temp_landzone_vendedores_db2.parquet'.
Arquivo 'bronze/db2/vendedores/vendedores_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db2.parquet' enviado para 'datalake/bronze/db2/vendedores/vendedores_db2.parquet'.
Arquivo 'landzone/vendedores_db3.parquet' baixado para 'temp_landzone_vendedores_db3.parquet'.
Arquivo 'bronze/db3/vendedores/vendedores_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db3.parquet' enviado para 'datalake/bronze/db3/vendedores/vendedores_db3.parquet'.

## LANDZONE <=> DATALAKE/BRONZE

In [32]:
from minio import Minio
from minio.error import S3Error
import duckdb
import os

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
landzone_bucket = "landzone"
bronze_bucket = "datalake"

# Função para baixar um arquivo do MinIO para o sistema local
def download_file(bucket_name, file_path, local_path):
    try:
        minio_client.fget_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{file_path}' baixado para '{local_path}'.")
    except S3Error as e:
        print(f"Erro ao baixar o arquivo '{file_path}': {e}")

# Função para fazer upload de um arquivo para o MinIO
def upload_file(bucket_name, file_path, local_path):
    try:
        minio_client.fput_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{local_path}' enviado para '{bucket_name}/{file_path}'.")
    except S3Error as e:
        print(f"Erro ao enviar o arquivo '{local_path}': {e}")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    if not minio_client.bucket_exists(bucket_name):
        print(f"Bucket '{bucket_name}' não existe.")
        return []
    
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except S3Error as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para realizar o upsert usando DuckDB
def upsert_parquet(landzone_file, bronze_file, output_file):
    conn = duckdb.connect()

    # Verifica se o arquivo bronze existe
    bronze_exists = os.path.exists(bronze_file)

    # Lê os arquivos Parquet
    landzone_df = conn.execute(f"SELECT * FROM read_parquet('{landzone_file}')").fetchdf()
    if bronze_exists:
        bronze_df = conn.execute(f"SELECT * FROM read_parquet('{bronze_file}')").fetchdf()
    else:
        bronze_df = None

    # Supondo que há uma coluna única para identificar registros (ex: id)
    primary_key = "id"  # Altere para a coluna correta

    if bronze_df is not None:
        upsert_query = f"""
        SELECT * FROM landzone_df
        UNION ALL
        SELECT * FROM bronze_df
        WHERE {primary_key} NOT IN (SELECT {primary_key} FROM landzone_df)
        """
        result_df = conn.execute(upsert_query).fetchdf()
    else:
        result_df = landzone_df  # Apenas insere os novos dados se não houver bronze

    # Salva o resultado em um novo arquivo Parquet
    result_df.to_parquet(output_file)
    print(f"Upsert concluído. Resultado salvo em '{output_file}'.")

    conn.close()

# Verifica se o bucket 'datalake' existe ou cria ele
if not minio_client.bucket_exists(bronze_bucket):
    minio_client.make_bucket(bronze_bucket)
    print(f"Bucket '{bronze_bucket}' criado com sucesso.")

# Lista todos os arquivos na 'landzone'
landzone_files = list_files(landzone_bucket)

# Processa cada arquivo na 'landzone'
for file_path in landzone_files:
    file_name = file_path.split("/")[-1]

    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_name and file_name.endswith(".parquet"):
        file_type = file_name.split("_db")[0]
        db_number = file_name.split("_")[-1].split(".")[0]  # Ex: db1

        # Caminho no bucket 'bronze' (correção aqui)
        destination_path = f"bronze/{db_number}/{file_name}"

        # Arquivos locais temporários
        local_landzone_file = f"temp_landzone_{file_name}"
        local_bronze_file = f"temp_bronze_{file_name}"
        local_output_file = f"temp_output_{file_name}"

        # Baixa o arquivo da 'landzone'
        download_file(landzone_bucket, file_path, local_landzone_file)

        # Verifica se o arquivo existe na 'bronze' antes de tentar baixá-lo
        try:
            minio_client.stat_object(bronze_bucket, destination_path)
            download_file(bronze_bucket, destination_path, local_bronze_file)
            bronze_exists = True
        except S3Error:
            print(f"Arquivo '{destination_path}' não encontrado na bronze. Será inserido diretamente.")
            bronze_exists = False

        # Realiza o upsert
        try:
            if bronze_exists:
                upsert_parquet(local_landzone_file, local_bronze_file, local_output_file)
                upload_file(bronze_bucket, destination_path, local_output_file)
            else:
                upload_file(bronze_bucket, destination_path, local_landzone_file)
        finally:
            # Remove arquivos temporários
            for temp_file in [local_landzone_file, local_bronze_file, local_output_file]:
                if os.path.exists(temp_file):
                    os.remove(temp_file)

Arquivo 'landzone/fornecedores_db1.parquet' baixado para 'temp_landzone_fornecedores_db1.parquet'.
Arquivo 'bronze/db1/fornecedores_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db1.parquet' enviado para 'datalake/bronze/db1/fornecedores_db1.parquet'.
Arquivo 'landzone/fornecedores_db2.parquet' baixado para 'temp_landzone_fornecedores_db2.parquet'.
Arquivo 'bronze/db2/fornecedores_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db2.parquet' enviado para 'datalake/bronze/db2/fornecedores_db2.parquet'.
Arquivo 'landzone/fornecedores_db3.parquet' baixado para 'temp_landzone_fornecedores_db3.parquet'.
Arquivo 'bronze/db3/fornecedores_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_fornecedores_db3.parquet' enviado para 'datalake/bronze/db3/fornecedores_db3.parquet'.
Arquivo 'landzone/produtos_db1.parquet' baixado para 'temp_landzone_produtos_db1.parquet'.
Arquivo 'bronze/db1/produtos_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db1.parquet' enviado para 'datalake/bronze/db1/produtos_db1.parquet'.
Arquivo 'landzone/produtos_db2.parquet' baixado para 'temp_landzone_produtos_db2.parquet'.
Arquivo 'bronze/db2/produtos_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db2.parquet' enviado para 'datalake/bronze/db2/produtos_db2.parquet'.
Arquivo 'landzone/produtos_db3.parquet' baixado para 'temp_landzone_produtos_db3.parquet'.
Arquivo 'bronze/db3/produtos_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_produtos_db3.parquet' enviado para 'datalake/bronze/db3/produtos_db3.parquet'.
Arquivo 'landzone/vendas_db1.parquet' baixado para 'temp_landzone_vendas_db1.parquet'.
Arquivo 'bronze/db1/vendas_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db1.parquet' enviado para 'datalake/bronze/db1/vendas_db1.parquet'.
Arquivo 'landzone/vendas_db2.parquet' baixado para 'temp_landzone_vendas_db2.parquet'.
Arquivo 'bronze/db2/vendas_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db2.parquet' enviado para 'datalake/bronze/db2/vendas_db2.parquet'.
Arquivo 'landzone/vendas_db3.parquet' baixado para 'temp_landzone_vendas_db3.parquet'.
Arquivo 'bronze/db3/vendas_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendas_db3.parquet' enviado para 'datalake/bronze/db3/vendas_db3.parquet'.
Arquivo 'landzone/vendedores_db1.parquet' baixado para 'temp_landzone_vendedores_db1.parquet'.
Arquivo 'bronze/db1/vendedores_db1.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db1.parquet' enviado para 'datalake/bronze/db1/vendedores_db1.parquet'.
Arquivo 'landzone/vendedores_db2.parquet' baixado para 'temp_landzone_vendedores_db2.parquet'.
Arquivo 'bronze/db2/vendedores_db2.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db2.parquet' enviado para 'datalake/bronze/db2/vendedores_db2.parquet'.
Arquivo 'landzone/vendedores_db3.parquet' baixado para 'temp_landzone_vendedores_db3.parquet'.
Arquivo 'bronze/db3/vendedores_db3.parquet' não encontrado na bronze. Será inserido diretamente.
Arquivo 'temp_landzone_vendedores_db3.parquet' enviado para 'datalake/bronze/db3/vendedores_db3.parquet'.

## silver

In [43]:
import duckdb
import pandas as pd
from minio import Minio
import os

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
datalake_bucket = "datalake"  # O bucket 'datalake' sem a barra
bronze_prefix = "bronze/"  # Prefixo para arquivos em 'bronze'
silver_prefix = "silver/"  # Prefixo para arquivos em 'silver'

# Função para baixar um arquivo do MinIO para o sistema local
def download_file(bucket_name, file_path, local_path):
    try:
        minio_client.fget_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{file_path}' baixado para '{local_path}'.")
    except Exception as e:
        print(f"Erro ao baixar o arquivo '{file_path}': {e}")

# Função para fazer upload de um arquivo para o MinIO
def upload_file(bucket_name, file_path, local_path):
    try:
        minio_client.fput_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{local_path}' enviado para '{bucket_name}/{file_path}'.")
    except Exception as e:
        print(f"Erro ao enviar o arquivo '{local_path}': {e}")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    if not minio_client.bucket_exists(bucket_name):
        print(f"Bucket '{bucket_name}' não existe.")
        return []
    
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except Exception as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Configuração do DuckDB
def upsert_to_silver(file_path):
    # Conectando ao DuckDB em memória
    con = duckdb.connect()

    # Baixar arquivo bronze para o local temporário
    local_bronze_file = f"temp_bronze_{file_path.split('/')[-1]}"
    download_file(datalake_bucket, file_path, local_bronze_file)

    # Carregar o arquivo .parquet em um DataFrame
    df = pd.read_parquet(local_bronze_file)

    # Criar tabela temporária para armazenar os dados da "bronze"
    con.execute("CREATE TABLE IF NOT EXISTS bronze_table AS SELECT * FROM df")

    # Verificar se o arquivo da 'silver' existe localmente
    silver_file = file_path.replace("bronze", "silver")
    silver_local_path = f"temp_silver_{file_path.split('/')[-1]}"
    
    if os.path.exists(silver_local_path):
        try:
            # Se existir, carregar o arquivo da 'silver'
            silver_df = pd.read_parquet(silver_local_path)
            print(f"Arquivo '{silver_local_path}' carregado com sucesso.")
        except Exception as e:
            print(f"Erro ao carregar o arquivo 'silver': {e}")
            silver_df = df  # Se falhar, criar um DataFrame vazio para upsert
    else:
        print(f"O arquivo '{silver_local_path}' não existe, criando um novo.")
        silver_df = df  # Se não existir, criar o DataFrame da "bronze"

    # Verificar os registros existentes e atualizar conforme necessário
    silver_df = silver_df.set_index("id").combine_first(df.set_index("id")).reset_index()

    # Salvar o arquivo da 'silver' após upsert
    silver_df.to_parquet(silver_local_path)

    # Fazer o upload do arquivo atualizado para o MinIO
    upload_file(datalake_bucket, silver_file, silver_local_path)

    # Remover os arquivos temporários locais
    if os.path.exists(local_bronze_file):
        os.remove(local_bronze_file)
    if os.path.exists(silver_local_path):
        os.remove(silver_local_path)

# Verifica se o bucket 'datalake' existe ou cria ele
if not minio_client.bucket_exists(datalake_bucket):
    minio_client.make_bucket(datalake_bucket)
    print(f"Bucket '{datalake_bucket}' criado com sucesso.")

# Lista todos os arquivos na 'bronze'
bronze_files = list_files(datalake_bucket, bronze_prefix)

# Processa cada arquivo na 'bronze'
for file_path in bronze_files:
    # Verifica se o arquivo segue o padrão esperado (ex: tipo_dbX.parquet)
    if "_db" in file_path and file_path.endswith(".parquet"):
        upsert_to_silver(file_path)

Arquivo 'bronze/db1/fornecedores_db1.parquet' baixado para 'temp_bronze_fornecedores_db1.parquet'.
O arquivo 'temp_silver_fornecedores_db1.parquet' não existe, criando um novo.
Arquivo 'temp_silver_fornecedores_db1.parquet' enviado para 'datalake/silver/db1/fornecedores_db1.parquet'.
Arquivo 'bronze/db1/produtos_db1.parquet' baixado para 'temp_bronze_produtos_db1.parquet'.
O arquivo 'temp_silver_produtos_db1.parquet' não existe, criando um novo.
Arquivo 'temp_silver_produtos_db1.parquet' enviado para 'datalake/silver/db1/produtos_db1.parquet'.
Arquivo 'bronze/db1/vendas_db1.parquet' baixado para 'temp_bronze_vendas_db1.parquet'.
O arquivo 'temp_silver_vendas_db1.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendas_db1.parquet' enviado para 'datalake/silver/db1/vendas_db1.parquet'.
Arquivo 'bronze/db1/vendedores_db1.parquet' baixado para 'temp_bronze_vendedores_db1.parquet'.
O arquivo 'temp_silver_vendedores_db1.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendedores_db1.parquet' enviado para 'datalake/silver/db1/vendedores_db1.parquet'.
Arquivo 'bronze/db2/fornecedores_db2.parquet' baixado para 'temp_bronze_fornecedores_db2.parquet'.
O arquivo 'temp_silver_fornecedores_db2.parquet' não existe, criando um novo.
Arquivo 'temp_silver_fornecedores_db2.parquet' enviado para 'datalake/silver/db2/fornecedores_db2.parquet'.
Arquivo 'bronze/db2/produtos_db2.parquet' baixado para 'temp_bronze_produtos_db2.parquet'.
O arquivo 'temp_silver_produtos_db2.parquet' não existe, criando um novo.
Arquivo 'temp_silver_produtos_db2.parquet' enviado para 'datalake/silver/db2/produtos_db2.parquet'.
Arquivo 'bronze/db2/vendas_db2.parquet' baixado para 'temp_bronze_vendas_db2.parquet'.
O arquivo 'temp_silver_vendas_db2.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendas_db2.parquet' enviado para 'datalake/silver/db2/vendas_db2.parquet'.
Arquivo 'bronze/db2/vendedores_db2.parquet' baixado para 'temp_bronze_vendedores_db2.parquet'.
O arquivo 'temp_silver_vendedores_db2.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendedores_db2.parquet' enviado para 'datalake/silver/db2/vendedores_db2.parquet'.
Arquivo 'bronze/db3/fornecedores_db3.parquet' baixado para 'temp_bronze_fornecedores_db3.parquet'.
O arquivo 'temp_silver_fornecedores_db3.parquet' não existe, criando um novo.
Arquivo 'temp_silver_fornecedores_db3.parquet' enviado para 'datalake/silver/db3/fornecedores_db3.parquet'.
Arquivo 'bronze/db3/produtos_db3.parquet' baixado para 'temp_bronze_produtos_db3.parquet'.
O arquivo 'temp_silver_produtos_db3.parquet' não existe, criando um novo.
Arquivo 'temp_silver_produtos_db3.parquet' enviado para 'datalake/silver/db3/produtos_db3.parquet'.
Arquivo 'bronze/db3/vendas_db3.parquet' baixado para 'temp_bronze_vendas_db3.parquet'.
O arquivo 'temp_silver_vendas_db3.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendas_db3.parquet' enviado para 'datalake/silver/db3/vendas_db3.parquet'.
Arquivo 'bronze/db3/vendedores_db3.parquet' baixado para 'temp_bronze_vendedores_db3.parquet'.
O arquivo 'temp_silver_vendedores_db3.parquet' não existe, criando um novo.
Arquivo 'temp_silver_vendedores_db3.parquet' enviado para 'datalake/silver/db3/vendedores_db3.parquet'.

## CAMADA SILVERANALITICS

In [44]:
import duckdb
import pandas as pd
from minio import Minio
import os

# Configuração do cliente MinIO
minio_client = Minio(
    "127.0.0.1:9001",  # URL do MinIO
    access_key="minioadmin",
    secret_key="minioadmin",
    secure=False
)

# Nomes dos buckets
datalake_bucket = "datalake"  # O bucket 'datalake' sem a barra
silver_prefix = "silver/"  # Prefixo para arquivos em 'silver'
silveranalitics_prefix = "silveranalitics/"  # Prefixo para arquivos em 'silveranalitics'

# Função para baixar um arquivo do MinIO para o sistema local
def download_file(bucket_name, file_path, local_path):
    try:
        minio_client.fget_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{file_path}' baixado para '{local_path}'.")
    except Exception as e:
        print(f"Erro ao baixar o arquivo '{file_path}': {e}")

# Função para fazer upload de um arquivo para o MinIO
def upload_file(bucket_name, file_path, local_path):
    try:
        minio_client.fput_object(bucket_name, file_path, local_path)
        print(f"Arquivo '{local_path}' enviado para '{bucket_name}/{file_path}'.")
    except Exception as e:
        print(f"Erro ao enviar o arquivo '{local_path}': {e}")

# Função para listar arquivos em um bucket
def list_files(bucket_name, prefix=""):
    if not minio_client.bucket_exists(bucket_name):
        print(f"Bucket '{bucket_name}' não existe.")
        return []
    
    try:
        objects = minio_client.list_objects(bucket_name, prefix=prefix, recursive=True)
        return [obj.object_name for obj in objects]
    except Exception as e:
        print(f"Erro ao listar arquivos no bucket '{bucket_name}': {e}")
        return []

# Função para fazer o upsert dos dados para o bucket silveranalitics
def upsert_to_silveranalitics():
    # Conectando ao DuckDB em memória
    con = duckdb.connect()

    # Baixar todos os arquivos na camada silver
    db_files = list_files(datalake_bucket, silver_prefix + "db1/")
    db_files += list_files(datalake_bucket, silver_prefix + "db2/")
    db_files += list_files(datalake_bucket, silver_prefix + "db3/")  # Adicione mais dbs se necessário

    # Agrupar os arquivos por tipo (fornecedores, produtos, etc.)
    file_types = set([f.split("/")[-1].split("_")[0] for f in db_files])  # Ex: fornecedores, produtos, etc.

    for file_type in file_types:
        # Filtrar os arquivos de acordo com o tipo
        type_files = [f for f in db_files if file_type in f and f.endswith(".parquet")]

        # DataFrame vazio para juntar os dados de cada tipo
        type_df = pd.DataFrame()

        for f in type_files:
            # Baixar e carregar os arquivos
            local_file = f"temp_{f.split('/')[-1]}"
            download_file(datalake_bucket, f, local_file)

            # Ler o arquivo .parquet
            temp_df = pd.read_parquet(local_file)
            type_df = pd.concat([type_df, temp_df], ignore_index=True)

            # Remover arquivo temporário
            if os.path.exists(local_file):
                os.remove(local_file)

        # Realizar o upsert (aqui estamos fazendo um exemplo de concatenação e remoção de duplicatas)
        type_df = type_df.drop_duplicates()

        # Definir o caminho do arquivo na camada silveranalitics
        silveranalitics_file = silveranalitics_prefix + f"{file_type}.parquet"

        # Salvar o arquivo atualizado na camada silveranalitics
        type_df.to_parquet(f"temp_{file_type}.parquet")

        # Fazer o upload para o MinIO
        upload_file(datalake_bucket, silveranalitics_file, f"temp_{file_type}.parquet")

        # Remover arquivos temporários locais
        if os.path.exists(f"temp_{file_type}.parquet"):
            os.remove(f"temp_{file_type}.parquet")

# Verifica se o bucket 'datalake' existe ou cria ele
if not minio_client.bucket_exists(datalake_bucket):
    minio_client.make_bucket(datalake_bucket)
    print(f"Bucket '{datalake_bucket}' criado com sucesso.")

# Verifica se o bucket 'silveranalitics' existe ou cria ele
if not minio_client.bucket_exists(silveranalitics_prefix):
    minio_client.make_bucket(silveranalitics_prefix)
    print(f"Bucket '{silveranalitics_prefix}' criado com sucesso.")

# Processa todos os arquivos da camada silver e faz o upsert na silveranalitics
upsert_to_silveranalitics()

ValueError: invalid bucket name silveranalitics/

In [3]:
import pandas as pd
df = pd.read_parquet("/Users/danielcarloss7s/Downloads/fornecedores_db1 (1).parquet")

ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

In [2]:
import pyarrow.parquet as pq

try:
    table = pq.read_table("/Volumes/MACBACKUP/workspaceDlake/dlake/temp_bronze_fornecedores_db1.parquet")
    df = table.to_pandas()
    df.to_csv("dados_recuperados.csv", index=False)
    print("Arquivo Parquet convertido para CSV.")
except Exception as e:
    print("Erro ao ler o Parquet:", e)

Erro ao ler o Parquet: Error creating dataset. Could not read schema from '/Volumes/MACBACKUP/workspaceDlake/dlake/temp_bronze_fornecedores_db1.parquet'. Is this a 'parquet' file?: Could not open Parquet input source '/Volumes/MACBACKUP/workspaceDlake/dlake/temp_bronze_fornecedores_db1.parquet': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.